//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Approval {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Approval() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Approval", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Approval.
        /// </summary>
        internal static string AcceptApproval {
            get {
                return ResourceManager.GetString("AcceptApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Date.
        /// </summary>
        internal static string ActiveDate {
            get {
                return ResourceManager.GetString("ActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Status.
        /// </summary>
        internal static string ActivityStatus {
            get {
                return ResourceManager.GetString("ActivityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Amt.
        /// </summary>
        internal static string ApprovalAmt {
            get {
                return ResourceManager.GetString("ApprovalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Member Invoice.
        /// </summary>
        internal static string ApprovalMemberInvoice {
            get {
                return ResourceManager.GetString("ApprovalMemberInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval waiting.
        /// </summary>
        internal static string ApprovalWaiting {
            get {
                return ResourceManager.GetString("ApprovalWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Service.
        /// </summary>
        internal static string ApproveService {
            get {
                return ResourceManager.GetString("ApproveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Home.
        /// </summary>
        internal static string BackToMainHome {
            get {
                return ResourceManager.GetString("BackToMainHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Approval.
        /// </summary>
        internal static string CheckApproval {
            get {
                return ResourceManager.GetString("CheckApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number.
        /// </summary>
        internal static string ClaimFormNumber {
            get {
                return ResourceManager.GetString("ClaimFormNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Services.
        /// </summary>
        internal static string ClaimServices {
            get {
                return ResourceManager.GetString("ClaimServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        internal static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive Date.
        /// </summary>
        internal static string DeactiveDate {
            get {
                return ResourceManager.GetString("DeactiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Claim Service.
        /// </summary>
        internal static string EditClaimService {
            get {
                return ResourceManager.GetString("EditClaimService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Print Cancel Approval.
        /// </summary>
        internal static string GoToPrintCancel {
            get {
                return ResourceManager.GetString("GoToPrintCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        internal static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Age.
        /// </summary>
        internal static string MemberAge {
            get {
                return ResourceManager.GetString("MemberAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Birth Date.
        /// </summary>
        internal static string MemberBirthDate {
            get {
                return ResourceManager.GetString("MemberBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Deductable.
        /// </summary>
        internal static string MemberDeductable {
            get {
                return ResourceManager.GetString("MemberDeductable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Deductable Percentage.
        /// </summary>
        internal static string MemberDeductablePercentage {
            get {
                return ResourceManager.GetString("MemberDeductablePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        internal static string MemberName {
            get {
                return ResourceManager.GetString("MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Validation.
        /// </summary>
        internal static string MemberValidation {
            get {
                return ResourceManager.GetString("MemberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval is Accepted..
        /// </summary>
        internal static string Msg_Accepted {
            get {
                return ResourceManager.GetString("Msg_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval is Accepted From Another Provider &lt;br&gt; You Can not Accept This Approval &lt;br&gt; Contact With CMC Please.
        /// </summary>
        internal static string Msg_AcceptedByAnother {
            get {
                return ResourceManager.GetString("Msg_AcceptedByAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select At Least One Service To Accept Approval..
        /// </summary>
        internal static string Msg_SelectOne {
            get {
                return ResourceManager.GetString("Msg_SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Member Have not Any Approval From CMC in Medi Gold , Please Contact With CMC !.
        /// </summary>
        internal static string NoApprovalMsg {
            get {
                return ResourceManager.GetString("NoApprovalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you Sure you want to Accept Approval ?.
        /// </summary>
        internal static string Q_Accept {
            get {
                return ResourceManager.GetString("Q_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Amt.
        /// </summary>
        internal static string RequestedAmt {
            get {
                return ResourceManager.GetString("RequestedAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Price.
        /// </summary>
        internal static string RequestedPrice {
            get {
                return ResourceManager.GetString("RequestedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Amt.
        /// </summary>
        internal static string ServiceAmt {
            get {
                return ResourceManager.GetString("ServiceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Modification.
        /// </summary>
        internal static string ServiceModification {
            get {
                return ResourceManager.GetString("ServiceModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Price.
        /// </summary>
        internal static string ServicePrice {
            get {
                return ResourceManager.GetString("ServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Qnt.
        /// </summary>
        internal static string ServiceQnt {
            get {
                return ResourceManager.GetString("ServiceQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex Type.
        /// </summary>
        internal static string SexType {
            get {
                return ResourceManager.GetString("SexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate member card, review approvals and accept approval.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
