//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DoctorClaimForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DoctorClaimForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DoctorClaimForm", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Claim Service.
        /// </summary>
        internal static string AddNewClaimService {
            get {
                return ResourceManager.GetString("AddNewClaimService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Service.
        /// </summary>
        internal static string AddNewService {
            get {
                return ResourceManager.GetString("AddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter card number.
        /// </summary>
        internal static string CardNumberPH {
            get {
                return ResourceManager.GetString("CardNumberPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Image.
        /// </summary>
        internal static string ClaimFormImage {
            get {
                return ResourceManager.GetString("ClaimFormImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductable Percentage.
        /// </summary>
        internal static string DeductPerc {
            get {
                return ResourceManager.GetString("DeductPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        internal static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type diagnosis.
        /// </summary>
        internal static string DiagnosisPH {
            get {
                return ResourceManager.GetString("DiagnosisPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Services.
        /// </summary>
        internal static string DoctorServicesTitle {
            get {
                return ResourceManager.GetString("DoctorServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type drug/service name.
        /// </summary>
        internal static string DrugPH {
            get {
                return ResourceManager.GetString("DrugPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Claim Service.
        /// </summary>
        internal static string EditClaimService {
            get {
                return ResourceManager.GetString("EditClaimService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD Number.
        /// </summary>
        internal static string ICDNumber {
            get {
                return ResourceManager.GetString("ICDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ICD code.
        /// </summary>
        internal static string ICDNumberPH {
            get {
                return ResourceManager.GetString("ICDNumberPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amt.
        /// </summary>
        internal static string InvoiceAmt {
            get {
                return ResourceManager.GetString("InvoiceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Member Invoice.
        /// </summary>
        internal static string InvoiceTitle {
            get {
                return ResourceManager.GetString("InvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labs.
        /// </summary>
        internal static string Labs {
            get {
                return ResourceManager.GetString("Labs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lab Services.
        /// </summary>
        internal static string LabServices {
            get {
                return ResourceManager.GetString("LabServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical History.
        /// </summary>
        internal static string MedicalHistory {
            get {
                return ResourceManager.GetString("MedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Data Content.
        /// </summary>
        internal static string MemberCardTitle {
            get {
                return ResourceManager.GetString("MemberCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Deductable.
        /// </summary>
        internal static string MemberDeduct {
            get {
                return ResourceManager.GetString("MemberDeduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        internal static string MemberName {
            get {
                return ResourceManager.GetString("MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type member name.
        /// </summary>
        internal static string MemberNamePH {
            get {
                return ResourceManager.GetString("MemberNamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Services.
        /// </summary>
        internal static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Claim Service.
        /// </summary>
        internal static string NewClaimService {
            get {
                return ResourceManager.GetString("NewClaimService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optical center.
        /// </summary>
        internal static string OpticalCenter {
            get {
                return ResourceManager.GetString("OpticalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optical Services.
        /// </summary>
        internal static string OpticalServices {
            get {
                return ResourceManager.GetString("OpticalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pharmacy.
        /// </summary>
        internal static string Pharmacy {
            get {
                return ResourceManager.GetString("Pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pharmacy Services.
        /// </summary>
        internal static string PharmacyServices {
            get {
                return ResourceManager.GetString("PharmacyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physiothrapy Services.
        /// </summary>
        internal static string PhysioServices {
            get {
                return ResourceManager.GetString("PhysioServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physiothrapy.
        /// </summary>
        internal static string Physiotherapy {
            get {
                return ResourceManager.GetString("Physiotherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider appearance.
        /// </summary>
        internal static string ProviderAppearance {
            get {
                return ResourceManager.GetString("ProviderAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quntity.
        /// </summary>
        internal static string Quntity {
            get {
                return ResourceManager.GetString("Quntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ClaimForm.
        /// </summary>
        internal static string RequestClaimForm {
            get {
                return ResourceManager.GetString("RequestClaimForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Price.
        /// </summary>
        internal static string RequestedPrice {
            get {
                return ResourceManager.GetString("RequestedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Services.
        /// </summary>
        internal static string ScanServices {
            get {
                return ResourceManager.GetString("ScanServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service list.
        /// </summary>
        internal static string ServiceList {
            get {
                return ResourceManager.GetString("ServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Note.
        /// </summary>
        internal static string ServiceNote {
            get {
                return ResourceManager.GetString("ServiceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type service name.
        /// </summary>
        internal static string ServicePH {
            get {
                return ResourceManager.GetString("ServicePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Price.
        /// </summary>
        internal static string ServicePrice {
            get {
                return ResourceManager.GetString("ServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Qnt.
        /// </summary>
        internal static string ServiceQnt {
            get {
                return ResourceManager.GetString("ServiceQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter member data, add services, upload claim form image, then request claim form.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Date.
        /// </summary>
        internal static string Tbl_ActiveDate {
            get {
                return ResourceManager.GetString("Tbl_ActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Status.
        /// </summary>
        internal static string Tbl_ActivityStatus {
            get {
                return ResourceManager.GetString("Tbl_ActivityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string Tbl_CardNumber {
            get {
                return ResourceManager.GetString("Tbl_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End Date.
        /// </summary>
        internal static string Tbl_ContractEnd {
            get {
                return ResourceManager.GetString("Tbl_ContractEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        internal static string Tbl_ContractNumber {
            get {
                return ResourceManager.GetString("Tbl_ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Start Date.
        /// </summary>
        internal static string Tbl_ContractStart {
            get {
                return ResourceManager.GetString("Tbl_ContractStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string Tbl_CustomerName {
            get {
                return ResourceManager.GetString("Tbl_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive Date.
        /// </summary>
        internal static string Tbl_DeactiveDate {
            get {
                return ResourceManager.GetString("Tbl_DeactiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        internal static string Tbl_MemberName {
            get {
                return ResourceManager.GetString("Tbl_MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Tbl_Plan {
            get {
                return ResourceManager.GetString("Tbl_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex Type.
        /// </summary>
        internal static string Tbl_SexType {
            get {
                return ResourceManager.GetString("Tbl_SexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ClaimForm.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
