//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InvoicesAudit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoicesAudit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InvoicesAudit", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Branches.
        /// </summary>
        internal static string Branch_All {
            get {
                return ResourceManager.GetString("Branch_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Audit Content.
        /// </summary>
        internal static string CardTitle {
            get {
                return ResourceManager.GetString("CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct Amt.
        /// </summary>
        internal static string Child_DeductAmt {
            get {
                return ResourceManager.GetString("Child_DeductAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference Amt.
        /// </summary>
        internal static string Child_DifferenceAmt {
            get {
                return ResourceManager.GetString("Child_DifferenceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amt.
        /// </summary>
        internal static string Child_DiscountAmt {
            get {
                return ResourceManager.GetString("Child_DiscountAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amt.
        /// </summary>
        internal static string Child_DueAmt {
            get {
                return ResourceManager.GetString("Child_DueAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Child_Edit {
            get {
                return ResourceManager.GetString("Child_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Amt.
        /// </summary>
        internal static string Child_RequestedAmt {
            get {
                return ResourceManager.GetString("Child_RequestedAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Child_Save {
            get {
                return ResourceManager.GetString("Child_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Amt.
        /// </summary>
        internal static string Child_ServiceAmt {
            get {
                return ResourceManager.GetString("Child_ServiceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string Child_ServiceName {
            get {
                return ResourceManager.GetString("Child_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Note.
        /// </summary>
        internal static string Child_ServiceNote {
            get {
                return ResourceManager.GetString("Child_ServiceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Qnt.
        /// </summary>
        internal static string Child_ServiceQnt {
            get {
                return ResourceManager.GetString("Child_ServiceQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Amt.
        /// </summary>
        internal static string Child_UnitAmt {
            get {
                return ResourceManager.GetString("Child_UnitAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string Col_BranchName {
            get {
                return ResourceManager.GetString("Col_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string Col_CardNumber {
            get {
                return ResourceManager.GetString("Col_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number.
        /// </summary>
        internal static string Col_ClaimFormNum {
            get {
                return ResourceManager.GetString("Col_ClaimFormNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim ID.
        /// </summary>
        internal static string Col_ClaimID {
            get {
                return ResourceManager.GetString("Col_ClaimID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Amt.
        /// </summary>
        internal static string Col_ContractAmt {
            get {
                return ResourceManager.GetString("Col_ContractAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductable Amt.
        /// </summary>
        internal static string Col_DeductAmt {
            get {
                return ResourceManager.GetString("Col_DeductAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference Amt.
        /// </summary>
        internal static string Col_DifferenceAmt {
            get {
                return ResourceManager.GetString("Col_DifferenceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amt.
        /// </summary>
        internal static string Col_DiscountAmt {
            get {
                return ResourceManager.GetString("Col_DiscountAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amt.
        /// </summary>
        internal static string Col_DueAmt {
            get {
                return ResourceManager.GetString("Col_DueAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Date.
        /// </summary>
        internal static string Col_ProcedureDate {
            get {
                return ResourceManager.GetString("Col_ProcedureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Amt.
        /// </summary>
        internal static string Col_RequestedAmt {
            get {
                return ResourceManager.GetString("Col_RequestedAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Expended services.
        /// </summary>
        internal static string GoExpended {
            get {
                return ResourceManager.GetString("GoExpended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to send Invoices to Accounting Department?.
        /// </summary>
        internal static string Msg_ConfirmSend {
            get {
                return ResourceManager.GetString("Msg_ConfirmSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid Requested Amount again..
        /// </summary>
        internal static string Msg_InvalidRequested {
            get {
                return ResourceManager.GetString("Msg_InvalidRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load invoices list..
        /// </summary>
        internal static string Msg_LoadFailed {
            get {
                return ResourceManager.GetString("Msg_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one invoice..
        /// </summary>
        internal static string Msg_SelectAtLeastOne {
            get {
                return ResourceManager.GetString("Msg_SelectAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error while sending to Accounting..
        /// </summary>
        internal static string Msg_ServerErrorSend {
            get {
                return ResourceManager.GetString("Msg_ServerErrorSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices have been sent successfully..
        /// </summary>
        internal static string Msg_SuccessSent {
            get {
                return ResourceManager.GetString("Msg_SuccessSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Pay.
        /// </summary>
        internal static string SendToPay {
            get {
                return ResourceManager.GetString("SendToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review invoices, edit requested amount, then send to Accounting.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Count.
        /// </summary>
        internal static string Sum_SelectedCount {
            get {
                return ResourceManager.GetString("Sum_SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Difference.
        /// </summary>
        internal static string Sum_SelectedDifference {
            get {
                return ResourceManager.GetString("Sum_SelectedDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Requested.
        /// </summary>
        internal static string Sum_SelectedRequested {
            get {
                return ResourceManager.GetString("Sum_SelectedRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Invoices.
        /// </summary>
        internal static string Sum_TotalInvoices {
            get {
                return ResourceManager.GetString("Sum_TotalInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Audit.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
    }
}
