//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MedicalHistory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MedicalHistory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MedicalHistory", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical History Overview.
        /// </summary>
        internal static string CardTitle {
            get {
                return ResourceManager.GetString("CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Col_Category {
            get {
                return ResourceManager.GetString("Col_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Number.
        /// </summary>
        internal static string Col_ClaimNumber {
            get {
                return ResourceManager.GetString("Col_ClaimNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Type.
        /// </summary>
        internal static string Col_ClaimType {
            get {
                return ResourceManager.GetString("Col_ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Col_Description {
            get {
                return ResourceManager.GetString("Col_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD Number.
        /// </summary>
        internal static string Col_ICDNumber {
            get {
                return ResourceManager.GetString("Col_ICDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Act.
        /// </summary>
        internal static string Col_MedicalAct {
            get {
                return ResourceManager.GetString("Col_MedicalAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Date.
        /// </summary>
        internal static string Col_ProcedureDate {
            get {
                return ResourceManager.GetString("Col_ProcedureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        internal static string Col_ProviderName {
            get {
                return ResourceManager.GetString("Col_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Code.
        /// </summary>
        internal static string Col_ServiceCode {
            get {
                return ResourceManager.GetString("Col_ServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string Col_ServiceName {
            get {
                return ResourceManager.GetString("Col_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Qnt.
        /// </summary>
        internal static string Col_ServiceQnt {
            get {
                return ResourceManager.GetString("Col_ServiceQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Medical Services.
        /// </summary>
        internal static string GoMedicalServices {
            get {
                return ResourceManager.GetString("GoMedicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical history overview for the selected card.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical History.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
