//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MemberSmartCardRequests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemberSmartCardRequests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MemberSmartCardRequests", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval waiting.
        /// </summary>
        internal static string ApprovalWaiting {
            get {
                return ResourceManager.GetString("ApprovalWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Member Request.
        /// </summary>
        internal static string BtnCancelMemberRequest {
            get {
                return ResourceManager.GetString("BtnCancelMemberRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Member Request.
        /// </summary>
        internal static string BtnShowMemberRequest {
            get {
                return ResourceManager.GetString("BtnShowMemberRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Approval.
        /// </summary>
        internal static string CheckApproval {
            get {
                return ResourceManager.GetString("CheckApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Services.
        /// </summary>
        internal static string ClaimServices {
            get {
                return ResourceManager.GetString("ClaimServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Image.
        /// </summary>
        internal static string CloseImage {
            get {
                return ResourceManager.GetString("CloseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Print Cancel APProval.
        /// </summary>
        internal static string GoPrintCancel {
            get {
                return ResourceManager.GetString("GoPrintCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Smart Card Requests Content.
        /// </summary>
        internal static string LegendContent {
            get {
                return ResourceManager.GetString("LegendContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Requests.
        /// </summary>
        internal static string MemberRequests {
            get {
                return ResourceManager.GetString("MemberRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Validation.
        /// </summary>
        internal static string MemberValidation {
            get {
                return ResourceManager.GetString("MemberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number is not Approved.
        /// </summary>
        internal static string MsgClaimFormNotApproved {
            get {
                return ResourceManager.GetString("MsgClaimFormNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Member Have not Any Approval From CMC in Medi Gold , Please Contact With CMC !.
        /// </summary>
        internal static string MsgMemberNoApproval {
            get {
                return ResourceManager.GetString("MsgMemberNoApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Member Requests is Requierd.
        /// </summary>
        internal static string MsgSelectMemberReqRequired {
            get {
                return ResourceManager.GetString("MsgSelectMemberReqRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        internal static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review, validate, and process member smart card requests..
        /// </summary>
        internal static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you Sure you want to Cancel Member Request ?.
        /// </summary>
        internal static string QCancelMemberRequest {
            get {
                return ResourceManager.GetString("QCancelMemberRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select ClaimForm Number--.
        /// </summary>
        internal static string SelectMemberRequest {
            get {
                return ResourceManager.GetString("SelectMemberRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Approval.
        /// </summary>
        internal static string ShowApproval {
            get {
                return ResourceManager.GetString("ShowApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Medical Services.
        /// </summary>
        internal static string ShowMedicalServices {
            get {
                return ResourceManager.GetString("ShowMedicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Smart Card Requests.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload New ClaimForm Image.
        /// </summary>
        internal static string UploadNewClaimImage {
            get {
                return ResourceManager.GetString("UploadNewClaimImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning !.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
