//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentInquiry {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentInquiry() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PaymentInquiry", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin fees.
        /// </summary>
        internal static string Col_AdminFees {
            get {
                return ResourceManager.GetString("Col_AdminFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number.
        /// </summary>
        internal static string Col_BatchNumber {
            get {
                return ResourceManager.GetString("Col_BatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amt.
        /// </summary>
        internal static string Col_DueAmt {
            get {
                return ResourceManager.GetString("Col_DueAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string Col_DueDate {
            get {
                return ResourceManager.GetString("Col_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method Name.
        /// </summary>
        internal static string Col_Method {
            get {
                return ResourceManager.GetString("Col_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Payment Amt..
        /// </summary>
        internal static string Col_NetPayment {
            get {
                return ResourceManager.GetString("Col_NetPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amt.
        /// </summary>
        internal static string Col_PaidAmt {
            get {
                return ResourceManager.GetString("Col_PaidAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay. Doc. No..
        /// </summary>
        internal static string Col_PayDocNo {
            get {
                return ResourceManager.GetString("Col_PayDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        internal static string Col_PaymentDate {
            get {
                return ResourceManager.GetString("Col_PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        internal static string Col_ProviderName {
            get {
                return ResourceManager.GetString("Col_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec Batch Amt.
        /// </summary>
        internal static string Col_RecBatchAmt {
            get {
                return ResourceManager.GetString("Col_RecBatchAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec Date.
        /// </summary>
        internal static string Col_RecDate {
            get {
                return ResourceManager.GetString("Col_RecDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Amt.
        /// </summary>
        internal static string Col_RestAmt {
            get {
                return ResourceManager.GetString("Col_RestAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Col_Show {
            get {
                return ResourceManager.GetString("Col_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Status.
        /// </summary>
        internal static string Col_Status {
            get {
                return ResourceManager.GetString("Col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.H.T.
        /// </summary>
        internal static string Col_WHT {
            get {
                return ResourceManager.GetString("Col_WHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Expanded Services.
        /// </summary>
        internal static string GoExpanded {
            get {
                return ResourceManager.GetString("GoExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Inquiry Data.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Status_Paid {
            get {
                return ResourceManager.GetString("Status_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly Paid.
        /// </summary>
        internal static string Status_PartlyPaid {
            get {
                return ResourceManager.GetString("Status_PartlyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string Status_Received {
            get {
                return ResourceManager.GetString("Status_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        internal static string Status_UnPaid {
            get {
                return ResourceManager.GetString("Status_UnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View provider payment batches And status.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Sum_PaidCount {
            get {
                return ResourceManager.GetString("Sum_PaidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Batches.
        /// </summary>
        internal static string Sum_TotalBatches {
            get {
                return ResourceManager.GetString("Sum_TotalBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid Amt.
        /// </summary>
        internal static string Sum_TotalPaid {
            get {
                return ResourceManager.GetString("Sum_TotalPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rest Amt.
        /// </summary>
        internal static string Sum_TotalRest {
            get {
                return ResourceManager.GetString("Sum_TotalRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        internal static string Sum_UnpaidCount {
            get {
                return ResourceManager.GetString("Sum_UnpaidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Inquiry.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
