//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrintCancelApproval {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintCancelApproval() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PrintCancelApproval", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Data.
        /// </summary>
        internal static string CardTitle {
            get {
                return ResourceManager.GetString("CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string Col_CardNumber {
            get {
                return ResourceManager.GetString("Col_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number.
        /// </summary>
        internal static string Col_ClaimFormNum {
            get {
                return ResourceManager.GetString("Col_ClaimFormNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Col_Delete {
            get {
                return ResourceManager.GetString("Col_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amt.
        /// </summary>
        internal static string Col_InvoiceAmt {
            get {
                return ResourceManager.GetString("Col_InvoiceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Deductable.
        /// </summary>
        internal static string Col_InvoiceDeduct {
            get {
                return ResourceManager.GetString("Col_InvoiceDeduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice ID.
        /// </summary>
        internal static string Col_InvoiceID {
            get {
                return ResourceManager.GetString("Col_InvoiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        internal static string Col_MemberName {
            get {
                return ResourceManager.GetString("Col_MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Col_Print {
            get {
                return ResourceManager.GetString("Col_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Date.
        /// </summary>
        internal static string Col_ProcedureDate {
            get {
                return ResourceManager.GetString("Col_ProcedureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string Col_Serial {
            get {
                return ResourceManager.GetString("Col_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Col_Show {
            get {
                return ResourceManager.GetString("Col_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Doctor ClaimForm.
        /// </summary>
        internal static string GoDoctorClaimForm {
            get {
                return ResourceManager.GetString("GoDoctorClaimForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Medical Services.
        /// </summary>
        internal static string GoMedicalServices {
            get {
                return ResourceManager.GetString("GoMedicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ModalClose {
            get {
                return ResourceManager.GetString("ModalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Services.
        /// </summary>
        internal static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your cancel reason here.
        /// </summary>
        internal static string Msg_CancelReasonAria {
            get {
                return ResourceManager.GetString("Msg_CancelReasonAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your cancel reason here....
        /// </summary>
        internal static string Msg_CancelReasonPlaceholder {
            get {
                return ResourceManager.GetString("Msg_CancelReasonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim cannot be deleted because it was sent to Accounting to pay..
        /// </summary>
        internal static string Msg_CannotDeleteSent {
            get {
                return ResourceManager.GetString("Msg_CannotDeleteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete invoice?.
        /// </summary>
        internal static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to print all invoices PDF?.
        /// </summary>
        internal static string Msg_ConfirmPrintAll {
            get {
                return ResourceManager.GetString("Msg_ConfirmPrintAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to print invoice PDF?.
        /// </summary>
        internal static string Msg_ConfirmPrintOne {
            get {
                return ResourceManager.GetString("Msg_ConfirmPrintOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice is deleted successfully..
        /// </summary>
        internal static string Msg_DeletedOk {
            get {
                return ResourceManager.GetString("Msg_DeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error in this claim..
        /// </summary>
        internal static string Msg_DeleteError {
            get {
                return ResourceManager.GetString("Msg_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid date range again..
        /// </summary>
        internal static string Msg_InvalidDateRange {
            get {
                return ResourceManager.GetString("Msg_InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot cancel claim form without entering a cancel reason..
        /// </summary>
        internal static string Msg_ReasonRequired {
            get {
                return ResourceManager.GetString("Msg_ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print All Invoices Pdf.
        /// </summary>
        internal static string PrintAll {
            get {
                return ResourceManager.GetString("PrintAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date Range.
        /// </summary>
        internal static string SelectDateRange {
            get {
                return ResourceManager.GetString("SelectDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date range to list invoices, then print or cancel.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Amt.
        /// </summary>
        internal static string Svc_Amt {
            get {
                return ResourceManager.GetString("Svc_Amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Deductable.
        /// </summary>
        internal static string Svc_Deduct {
            get {
                return ResourceManager.GetString("Svc_Deduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string Svc_Name {
            get {
                return ResourceManager.GetString("Svc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Note.
        /// </summary>
        internal static string Svc_Note {
            get {
                return ResourceManager.GetString("Svc_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Price.
        /// </summary>
        internal static string Svc_Price {
            get {
                return ResourceManager.GetString("Svc_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Qnt.
        /// </summary>
        internal static string Svc_Qnt {
            get {
                return ResourceManager.GetString("Svc_Qnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string Svc_Serial {
            get {
                return ResourceManager.GetString("Svc_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print &amp; Cancel Invoice.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
