//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrintCancelClaimForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintCancelClaimForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PrintCancelClaimForm", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Date.
        /// </summary>
        internal static string ActiveDate {
            get {
                return ResourceManager.GetString("ActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Status.
        /// </summary>
        internal static string ActivityStatus {
            get {
                return ResourceManager.GetString("ActivityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Service.
        /// </summary>
        internal static string AddNewService {
            get {
                return ResourceManager.GetString("AddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Second Diagnosis.
        /// </summary>
        internal static string AddSecondDiagnosis {
            get {
                return ResourceManager.GetString("AddSecondDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Services &amp; Diagnoses.
        /// </summary>
        internal static string AddServicesTitle {
            get {
                return ResourceManager.GetString("AddServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Third Diagnosis.
        /// </summary>
        internal static string AddThirdDiagnosis {
            get {
                return ResourceManager.GetString("AddThirdDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Service Done.
        /// </summary>
        internal static string ApprovalDone {
            get {
                return ResourceManager.GetString("ApprovalDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Services Stopped.
        /// </summary>
        internal static string ApprovalStopped {
            get {
                return ResourceManager.GetString("ApprovalStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Services Waiting.
        /// </summary>
        internal static string ApprovalWaiting {
            get {
                return ResourceManager.GetString("ApprovalWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Back to Main Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Birth Date.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Card Number.
        /// </summary>
        internal static string CardPlaceholder {
            get {
                return ResourceManager.GetString("CardPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Validation.
        /// </summary>
        internal static string CheckValidation {
            get {
                return ResourceManager.GetString("CheckValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ClaimForm Image Content.
        /// </summary>
        internal static string ClaimFormImageContent {
            get {
                return ResourceManager.GetString("ClaimFormImageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number.
        /// </summary>
        internal static string ClaimFormNumber {
            get {
                return ResourceManager.GetString("ClaimFormNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number.
        /// </summary>
        internal static string ClaimFormNumberLabel {
            get {
                return ResourceManager.GetString("ClaimFormNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ClaimForm Number.
        /// </summary>
        internal static string ClaimFormPlaceholder {
            get {
                return ResourceManager.GetString("ClaimFormPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForms List.
        /// </summary>
        internal static string ClaimFormsList {
            get {
                return ResourceManager.GetString("ClaimFormsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Image.
        /// </summary>
        internal static string CloseImage {
            get {
                return ResourceManager.GetString("CloseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        internal static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive Date.
        /// </summary>
        internal static string DeactiveDate {
            get {
                return ResourceManager.GetString("DeactiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ClaimForm Image.
        /// </summary>
        internal static string DeleteClaimFormImage {
            get {
                return ResourceManager.GetString("DeleteClaimFormImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Second Diagnosis.
        /// </summary>
        internal static string DeleteSecondDiagnosis {
            get {
                return ResourceManager.GetString("DeleteSecondDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Third Diagnosis.
        /// </summary>
        internal static string DeleteThirdDiagnosis {
            get {
                return ResourceManager.GetString("DeleteThirdDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type diagnosis.
        /// </summary>
        internal static string DiagnosisPlaceholder {
            get {
                return ResourceManager.GetString("DiagnosisPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Claim Service.
        /// </summary>
        internal static string EditClaimService {
            get {
                return ResourceManager.GetString("EditClaimService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Diagnosis.
        /// </summary>
        internal static string FirstDiagnosis {
            get {
                return ResourceManager.GetString("FirstDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to ClaimForm Approved ».
        /// </summary>
        internal static string GoApproved {
            get {
                return ResourceManager.GetString("GoApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        internal static string MemberName {
            get {
                return ResourceManager.GetString("MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Validation.
        /// </summary>
        internal static string MemberValidation {
            get {
                return ResourceManager.GetString("MemberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Member Card.
        /// </summary>
        internal static string MemberValidationTitle {
            get {
                return ResourceManager.GetString("MemberValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Services.
        /// </summary>
        internal static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch is Added Full Claims.
        /// </summary>
        internal static string Msg_BatchFull {
            get {
                return ResourceManager.GetString("Msg_BatchFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not Correct &lt;br&gt; User can not access for this Card Number &lt;br&gt; Please contact CMC.
        /// </summary>
        internal static string Msg_CardNotAllowed_Suffix {
            get {
                return ResourceManager.GetString("Msg_CardNotAllowed_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not Correct &lt;br&gt; Please enter Card Number again.
        /// </summary>
        internal static string Msg_CardNotCorrect_Suffix {
            get {
                return ResourceManager.GetString("Msg_CardNotCorrect_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number is Deleted Successfully.
        /// </summary>
        internal static string Msg_Deleted {
            get {
                return ResourceManager.GetString("Msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number can not be deleted because Provider made approval. If you want delete, call CMC..
        /// </summary>
        internal static string Msg_DeleteNotAllowed1 {
            get {
                return ResourceManager.GetString("Msg_DeleteNotAllowed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number can not be deleted because different provider. If you want delete, call CMC..
        /// </summary>
        internal static string Msg_DeleteNotAllowed2 {
            get {
                return ResourceManager.GetString("Msg_DeleteNotAllowed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number is not Approved.
        /// </summary>
        internal static string Msg_NotApproved {
            get {
                return ResourceManager.GetString("Msg_NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Correct Service Name.
        /// </summary>
        internal static string Msg_SelectCorrectService {
            get {
                return ResourceManager.GetString("Msg_SelectCorrectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Form is sent to approve from CMC successfully.
        /// </summary>
        internal static string Msg_SentToCMC {
            get {
                return ResourceManager.GetString("Msg_SentToCMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Service is Added Since while in Provider Services..
        /// </summary>
        internal static string Msg_ServiceExists {
            get {
                return ResourceManager.GetString("Msg_ServiceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Service is inserted to Services Successfully.
        /// </summary>
        internal static string Msg_ServiceInserted {
            get {
                return ResourceManager.GetString("Msg_ServiceInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service Name is Required.
        /// </summary>
        internal static string Msg_ServiceRequired {
            get {
                return ResourceManager.GetString("Msg_ServiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Service is updated..
        /// </summary>
        internal static string Msg_ServiceUpdated {
            get {
                return ResourceManager.GetString("Msg_ServiceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Claim Service.
        /// </summary>
        internal static string NewClaimService {
            get {
                return ResourceManager.GetString("NewClaimService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        internal static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Date.
        /// </summary>
        internal static string ProcedureDate {
            get {
                return ResourceManager.GetString("ProcedureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Services.
        /// </summary>
        internal static string ProviderServices {
            get {
                return ResourceManager.GetString("ProviderServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Delete ClaimForm Number?.
        /// </summary>
        internal static string Q_DeleteClaimForm {
            get {
                return ResourceManager.GetString("Q_DeleteClaimForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete:.
        /// </summary>
        internal static string Q_DeleteRow {
            get {
                return ResourceManager.GetString("Q_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently sent Claim Form to approve from CMC. Are you sure you want to send?.
        /// </summary>
        internal static string Q_SendToCMC {
            get {
                return ResourceManager.GetString("Q_SendToCMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse Note.
        /// </summary>
        internal static string RefuseNote {
            get {
                return ResourceManager.GetString("RefuseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approval.
        /// </summary>
        internal static string RequestApproval {
            get {
                return ResourceManager.GetString("RequestApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Price.
        /// </summary>
        internal static string RequestedPrice {
            get {
                return ResourceManager.GetString("RequestedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Diagnosis.
        /// </summary>
        internal static string SecondDiagnosis {
            get {
                return ResourceManager.GetString("SecondDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type service name.
        /// </summary>
        internal static string ServicePlaceholder {
            get {
                return ResourceManager.GetString("ServicePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Price.
        /// </summary>
        internal static string ServicePrice {
            get {
                return ResourceManager.GetString("ServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Qnt.
        /// </summary>
        internal static string ServiceQnt {
            get {
                return ResourceManager.GetString("ServiceQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex Type.
        /// </summary>
        internal static string SexType {
            get {
                return ResourceManager.GetString("SexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ClaimForm Image.
        /// </summary>
        internal static string ShowClaimFormImage {
            get {
                return ResourceManager.GetString("ShowClaimFormImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate member, view claim form images, add services, and request approval.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Diagnosis.
        /// </summary>
        internal static string ThirdDiagnosis {
            get {
                return ResourceManager.GetString("ThirdDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Services.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload New ClaimForm Image.
        /// </summary>
        internal static string UploadNewClaimFormImage {
            get {
                return ResourceManager.GetString("UploadNewClaimFormImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning !.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
