//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProviderClaimFormApproved {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProviderClaimFormApproved() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProviderClaimFormApproved", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept ClaimForm &amp; Print Invoice.
        /// </summary>
        internal static string ApprovePrint {
            get {
                return ResourceManager.GetString("ApprovePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel ClaimForm.
        /// </summary>
        internal static string CancelClaim {
            get {
                return ResourceManager.GetString("CancelClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ClaimForm Image.
        /// </summary>
        internal static string CardTitle {
            get {
                return ResourceManager.GetString("CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Form Amt.
        /// </summary>
        internal static string ClaimFormAmt {
            get {
                return ResourceManager.GetString("ClaimFormAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number.
        /// </summary>
        internal static string ClaimFormNumber {
            get {
                return ResourceManager.GetString("ClaimFormNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Image.
        /// </summary>
        internal static string CloseImage {
            get {
                return ResourceManager.GetString("CloseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Deductable.
        /// </summary>
        internal static string DeductAmt {
            get {
                return ResourceManager.GetString("DeductAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Deductable Percentage.
        /// </summary>
        internal static string DeductPct {
            get {
                return ResourceManager.GetString("DeductPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Diagnosis.
        /// </summary>
        internal static string Diag1 {
            get {
                return ResourceManager.GetString("Diag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Diagnosis.
        /// </summary>
        internal static string Diag2 {
            get {
                return ResourceManager.GetString("Diag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Diagnosis.
        /// </summary>
        internal static string Diag3 {
            get {
                return ResourceManager.GetString("Diag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Medical Services.
        /// </summary>
        internal static string GoMedicalServices {
            get {
                return ResourceManager.GetString("GoMedicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First ICD Number.
        /// </summary>
        internal static string ICD1 {
            get {
                return ResourceManager.GetString("ICD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second ICD Number.
        /// </summary>
        internal static string ICD2 {
            get {
                return ResourceManager.GetString("ICD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third ICD Number.
        /// </summary>
        internal static string ICD3 {
            get {
                return ResourceManager.GetString("ICD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Member Invoice.
        /// </summary>
        internal static string MemberInvoice {
            get {
                return ResourceManager.GetString("MemberInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number is not exist.
        /// </summary>
        internal static string Msg_NotExist {
            get {
                return ResourceManager.GetString("Msg_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        internal static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to approve ClaimForm?.
        /// </summary>
        internal static string Q_Approve {
            get {
                return ResourceManager.GetString("Q_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel ClaimForm?.
        /// </summary>
        internal static string Q_Cancel {
            get {
                return ResourceManager.GetString("Q_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to resend ClaimForm to CMC again?.
        /// </summary>
        internal static string Q_Resend {
            get {
                return ResourceManager.GetString("Q_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse Note.
        /// </summary>
        internal static string RefuseNote {
            get {
                return ResourceManager.GetString("RefuseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Price.
        /// </summary>
        internal static string RequestedPrice {
            get {
                return ResourceManager.GetString("RequestedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend To CMC.
        /// </summary>
        internal static string ResendCMC {
            get {
                return ResourceManager.GetString("ResendCMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select ClaimForm Number --.
        /// </summary>
        internal static string SelectClaimForm {
            get {
                return ResourceManager.GetString("SelectClaimForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Amt.
        /// </summary>
        internal static string ServiceAmt {
            get {
                return ResourceManager.GetString("ServiceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Price.
        /// </summary>
        internal static string ServicePrice {
            get {
                return ResourceManager.GetString("ServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Qnt.
        /// </summary>
        internal static string ServiceQnt {
            get {
                return ResourceManager.GetString("ServiceQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Services Done.
        /// </summary>
        internal static string ServicesDone {
            get {
                return ResourceManager.GetString("ServicesDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Services Stopped.
        /// </summary>
        internal static string ServicesStopped {
            get {
                return ResourceManager.GetString("ServicesStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ClaimForm Image.
        /// </summary>
        internal static string ShowImage {
            get {
                return ResourceManager.GetString("ShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ClaimForm then view image and approve/cancel/resend.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider ClaimForm Approved.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
