//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProviderExpandedServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProviderExpandedServices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProviderExpandedServices", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Branches.
        /// </summary>
        internal static string Branch_All {
            get {
                return ResourceManager.GetString("Branch_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string Col_BranchName {
            get {
                return ResourceManager.GetString("Col_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string Col_CardNumber {
            get {
                return ResourceManager.GetString("Col_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number.
        /// </summary>
        internal static string Col_ClaimFormNum {
            get {
                return ResourceManager.GetString("Col_ClaimFormNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim ID.
        /// </summary>
        internal static string Col_ClaimID {
            get {
                return ResourceManager.GetString("Col_ClaimID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Amt.
        /// </summary>
        internal static string Col_ContractAmt {
            get {
                return ResourceManager.GetString("Col_ContractAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductable Amt.
        /// </summary>
        internal static string Col_DeductAmt {
            get {
                return ResourceManager.GetString("Col_DeductAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference Amt.
        /// </summary>
        internal static string Col_DifferenceAmt {
            get {
                return ResourceManager.GetString("Col_DifferenceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amt.
        /// </summary>
        internal static string Col_DiscountAmt {
            get {
                return ResourceManager.GetString("Col_DiscountAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amt.
        /// </summary>
        internal static string Col_DueAmt {
            get {
                return ResourceManager.GetString("Col_DueAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Date.
        /// </summary>
        internal static string Col_ProcedureDate {
            get {
                return ResourceManager.GetString("Col_ProcedureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Amt.
        /// </summary>
        internal static string Col_RequestedAmt {
            get {
                return ResourceManager.GetString("Col_RequestedAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Payment Inquiry.
        /// </summary>
        internal static string GoPaymentInquiry {
            get {
                return ResourceManager.GetString("GoPaymentInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expended services.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover To Audit.
        /// </summary>
        internal static string RecoverToAudit {
            get {
                return ResourceManager.GetString("RecoverToAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Count.
        /// </summary>
        internal static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Requested Amt.
        /// </summary>
        internal static string SelectedRequested {
            get {
                return ResourceManager.GetString("SelectedRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Pay.
        /// </summary>
        internal static string SendToPay {
            get {
                return ResourceManager.GetString("SendToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select invoices and send to accounting.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Claims.
        /// </summary>
        internal static string Sum_TotalClaims {
            get {
                return ResourceManager.GetString("Sum_TotalClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Due.
        /// </summary>
        internal static string Sum_TotalDue {
            get {
                return ResourceManager.GetString("Sum_TotalDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Requested.
        /// </summary>
        internal static string Sum_TotalRequested {
            get {
                return ResourceManager.GetString("Sum_TotalRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded Services.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
    }
}
