//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShowBatchData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShowBatchData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ShowBatchData", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        internal static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Payment Inquiry.
        /// </summary>
        internal static string BackToPayments {
            get {
                return ResourceManager.GetString("BackToPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string BatchNo {
            get {
                return ResourceManager.GetString("BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct Amt.
        /// </summary>
        internal static string Child_DeductAmt {
            get {
                return ResourceManager.GetString("Child_DeductAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference Amt.
        /// </summary>
        internal static string Child_DifferenceAmt {
            get {
                return ResourceManager.GetString("Child_DifferenceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amt.
        /// </summary>
        internal static string Child_DiscountAmt {
            get {
                return ResourceManager.GetString("Child_DiscountAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amt.
        /// </summary>
        internal static string Child_DueAmt {
            get {
                return ResourceManager.GetString("Child_DueAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Amt.
        /// </summary>
        internal static string Child_RequestedAmt {
            get {
                return ResourceManager.GetString("Child_RequestedAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Amt.
        /// </summary>
        internal static string Child_ServiceAmt {
            get {
                return ResourceManager.GetString("Child_ServiceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string Child_ServiceName {
            get {
                return ResourceManager.GetString("Child_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Note.
        /// </summary>
        internal static string Child_ServiceNote {
            get {
                return ResourceManager.GetString("Child_ServiceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Qnt.
        /// </summary>
        internal static string Child_ServiceQnt {
            get {
                return ResourceManager.GetString("Child_ServiceQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Details.
        /// </summary>
        internal static string Child_Title {
            get {
                return ResourceManager.GetString("Child_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Amt.
        /// </summary>
        internal static string Child_UnitAmt {
            get {
                return ResourceManager.GetString("Child_UnitAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string Col_BranchName {
            get {
                return ResourceManager.GetString("Col_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string Col_CardNumber {
            get {
                return ResourceManager.GetString("Col_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimForm Number.
        /// </summary>
        internal static string Col_ClaimFormNum {
            get {
                return ResourceManager.GetString("Col_ClaimFormNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim ID.
        /// </summary>
        internal static string Col_ClaimID {
            get {
                return ResourceManager.GetString("Col_ClaimID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Amt.
        /// </summary>
        internal static string Col_ContractAmt {
            get {
                return ResourceManager.GetString("Col_ContractAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductable Amt.
        /// </summary>
        internal static string Col_DeductAmt {
            get {
                return ResourceManager.GetString("Col_DeductAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference Amt.
        /// </summary>
        internal static string Col_DifferenceAmt {
            get {
                return ResourceManager.GetString("Col_DifferenceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amt.
        /// </summary>
        internal static string Col_DiscountAmt {
            get {
                return ResourceManager.GetString("Col_DiscountAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amt.
        /// </summary>
        internal static string Col_DueAmt {
            get {
                return ResourceManager.GetString("Col_DueAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        internal static string Col_MemberName {
            get {
                return ResourceManager.GetString("Col_MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Date.
        /// </summary>
        internal static string Col_ProcedureDate {
            get {
                return ResourceManager.GetString("Col_ProcedureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Amt.
        /// </summary>
        internal static string Col_RequestedAmt {
            get {
                return ResourceManager.GetString("Col_RequestedAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the left icon to show services details.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Content Data.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View batch claims and services details.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Data.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
