//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccEntryCtr
    {
        public int EntryCtrID { get; set; }
        public int JournalEntryID { get; set; }
        public int CtrID { get; set; }
        public int CtrTypeID { get; set; }
    }
}
