//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccJournalEntry
    {
        public int JournalEntryID { get; set; }
        public int JournalID { get; set; }
        public decimal EntryAmt { get; set; }
        public int EntryTypeID { get; set; }
        public string EntryDescription { get; set; }
        public string AccNum { get; set; }
    }
}
