//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingMasterSheet
    {
        public Nullable<decimal> Expr1 { get; set; }
        public decimal MemberPermuimAmt { get; set; }
        public string ContractNumber { get; set; }
        public string PlanTypeName { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
