//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccPayment
    {
        public int PayamentID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmt { get; set; }
        public int PaymentMethodID { get; set; }
        public int BankAccID { get; set; }
        public string PaymentDocNum { get; set; }
        public string BeneficiaryName { get; set; }
        public string BenBankName { get; set; }
        public string BenAccNumber { get; set; }
        public int IssuedBy { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int ApprovedBy { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public string PaymentInWord { get; set; }
        public bool IsActive { get; set; }
        public string TranseferNotes { get; set; }
        public int CancelUserID { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    }
}
