//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccRecInvoice
    {
        public int InvoiceID { get; set; }
        public int AccRecScheduleID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNum { get; set; }
        public string InvoiceAltNum { get; set; }
        public int PrimaryMembers { get; set; }
        public int AdditonMembers { get; set; }
        public int DeletionMembers { get; set; }
        public decimal AdminFeesAmt { get; set; }
        public decimal AdditionFeesAmt { get; set; }
        public decimal TotalFeesAmt { get; set; }
        public decimal VATAmt { get; set; }
        public decimal WHTAmt { get; set; }
        public decimal NetInvoiceAmt { get; set; }
        public string NetInvoiceChar { get; set; }
        public decimal FundPeriodAmt { get; set; }
        public decimal FundAdditionAmt { get; set; }
        public decimal FundDeletionAmt { get; set; }
        public decimal FundNetAmt { get; set; }
        public string FundNetChar { get; set; }
        public int InvoiceStatusID { get; set; }
        public int InvoiceTypeID { get; set; }
        public decimal PrimayFundAmt { get; set; }
        public decimal HumFundAmt { get; set; }
        public int IssuedBy { get; set; }
        public int ApprovedBy { get; set; }
        public decimal BrokerComAmt { get; set; }
    }
}
