//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccRecBatchRep
    {
        public int RecBatchID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string BatchNumber { get; set; }
        public string ProviderName { get; set; }
        public string ProviderNumber { get; set; }
        public Nullable<decimal> BatchClaimedAmt { get; set; }
        public Nullable<decimal> BatchDeductAmt { get; set; }
        public Nullable<decimal> BatchDiscountAmt { get; set; }
        public Nullable<decimal> BatchMedical_Deduct { get; set; }
        public Nullable<decimal> BatchDueAmt { get; set; }
        public Nullable<int> ClaimsNum { get; set; }
        public string ProviderCatName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<decimal> BatchRequestedAmt { get; set; }
        public Nullable<decimal> BatchDifferenceAmt { get; set; }
        public Nullable<decimal> BatchNetDueAmt { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<decimal> BatchAuditDeductAmt { get; set; }
        public string ProviderCode { get; set; }
    }
}
