//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccRecSchedule
    {
        public int AccRecScheduleID { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public int ContractID { get; set; }
        public bool IsReceived { get; set; }
        public int ScheduleNum { get; set; }
    }
}
