//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitySearchGridQuery
    {
        public string CustomerName { get; set; }
        public string ActivityTypeName { get; set; }
        public string Comment { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public System.DateTime StampDate { get; set; }
        public int SalesmanID { get; set; }
    }
}
