//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityData
    {
        public int ActivityID { get; set; }
        public int ActivityTypeID { get; set; }
        public int UserID { get; set; }
        public int CustomerID { get; set; }
        public string Comment { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public System.DateTime StampDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> SubStatusID { get; set; }
        public Nullable<int> CCGroupID { get; set; }
        public Nullable<bool> IsReminder { get; set; }
    }
}
