//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertCMCData
    {
        public int AlertCMCID { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public string CardNumber { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> BranchID { get; set; }
    }
}
