//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalView
    {
        public Nullable<int> ApprovalID { get; set; }
        public int CustomerID { get; set; }
        public int ProviderID { get; set; }
        public int ContractMemberdID { get; set; }
        public Nullable<long> ApprovalCode { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public int ClaimServiceID { get; set; }
        public Nullable<decimal> ApprovalAmt { get; set; }
        public Nullable<decimal> DeductPer { get; set; }
        public decimal DeductAmt { get; set; }
        public string Diagnosis { get; set; }
        public string ICDCode { get; set; }
        public string Notes { get; set; }
        public string CardNumber { get; set; }
        public string CustomerCode { get; set; }
        public string ProviderCode { get; set; }
        public string ContractNum { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string ClaimID { get; set; }
        public string BarchID { get; set; }
        public string ApprovalType { get; set; }
        public string ProviderName { get; set; }
        public string CustomerName { get; set; }
        public string MemberName { get; set; }
        public Nullable<double> SerialNum { get; set; }
        public string ApprovalStatusVar { get; set; }
    }
}
