//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVersion
    {
        public int App_Version_Id { get; set; }
        public string Version_Name { get; set; }
        public int Version_Code { get; set; }
        public bool Madatory_Flag { get; set; }
        public System.DateTime Publish_Date { get; set; }
        public string Subject_Ar { get; set; }
        public string Subject_En { get; set; }
        public string body_Ar { get; set; }
        public string body_En { get; set; }
        public string Operating_System_Code { get; set; }
        public string App_Type_Code { get; set; }
        public string Note { get; set; }
        public bool Enabled_Flag { get; set; }
        public int Version_No { get; set; }
        public System.DateTime Create_Date { get; set; }
        public int Create_By { get; set; }
        public System.DateTime Update_Date { get; set; }
        public int Update_By { get; set; }
    }
}
