//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_190200070
    {
        public int ClaimID { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public string CustomerName { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public string ContractNum { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public decimal ServiceQnt { get; set; }
        public decimal ServiceUnitAmt { get; set; }
        public decimal ClaimedAmt { get; set; }
        public decimal DeductAmt { get; set; }
        public decimal DiscountAmt { get; set; }
        public decimal FDiscountAmt { get; set; }
        public decimal MedicalDeductAmt { get; set; }
        public decimal DueAmt { get; set; }
        public decimal RequestedAmt { get; set; }
        public decimal DifferenceAmt { get; set; }
        public string RejectNotes { get; set; }
        public string claimservicename { get; set; }
        public string BatchNumber { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> RecBatchID { get; set; }
        public Nullable<int> ClaimServiceID { get; set; }
    }
}
