//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchEntryView
    {
        public Nullable<int> totalClaimsInBatch { get; set; }
        public string BatchNumber { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> MaxD { get; set; }
        public Nullable<System.DateTime> MinD { get; set; }
        public Nullable<int> ClaimsNum { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<int> RecBatchID { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> Rate { get; set; }
    }
}
