//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelReasonData
    {
        public int CancelReasonID { get; set; }
        public int ClaimID { get; set; }
        public long ClaimFormNum { get; set; }
        public int ContractMemberID { get; set; }
        public int UserID { get; set; }
        public string CardNumber { get; set; }
        public int ProviderID { get; set; }
        public string ProviderName { get; set; }
        public string BranchName { get; set; }
        public int BranchID { get; set; }
        public System.DateTime CancelReasonDate { get; set; }
        public string CancelReasonMessage { get; set; }
    }
}
