//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class chronicmembersview
    {
        public string CustomerName { get; set; }
        public int ChronicTemplateID { get; set; }
        public System.DateTime ScDate { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public string MemberICDCode { get; set; }
        public string MemberICDName { get; set; }
        public string ServiceName { get; set; }
        public string ProviderName { get; set; }
        public string MedDrugName { get; set; }
        public decimal NoOfUnits { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
        public string DrugsICD { get; set; }
        public string DrugICDName { get; set; }
        public string ContractNumber { get; set; }
    }
}
