//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsByRecBatchView
    {
        public int ClaimID { get; set; }
        public int RecBatchID { get; set; }
        public long ClaimFormNum { get; set; }
        public string CardNumber { get; set; }
        public string MemberName { get; set; }
        public System.DateTime ProcedureDate { get; set; }
        public decimal TClaimAmt { get; set; }
        public decimal TRequestedAmt { get; set; }
        public decimal NetClaimedAmt { get; set; }
        public decimal TDifferenceAmt { get; set; }
    }
}
