//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsContractOut
    {
        public int ClaimID { get; set; }
        public Nullable<int> RecBatchID { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public int ContractID { get; set; }
        public string ContractNumber { get; set; }
        public int ContractMemberID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<decimal> NetClaimedAmt { get; set; }
    }
}
