//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMApprovalInquiry
    {
        public string CustomerName { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public string ProviderName { get; set; }
        public Nullable<long> ApprovalCode { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> ApprovalAmt { get; set; }
        public Nullable<decimal> DeductPer { get; set; }
        public Nullable<decimal> DeductAmt { get; set; }
        public string ICDCode { get; set; }
        public string Diagnosis { get; set; }
        public string StatusName { get; set; }
        public string Notes { get; set; }
        public string Approvalmemo { get; set; }
        public int ApprovalID { get; set; }
        public Nullable<int> ContractMemberID { get; set; }
    }
}
