//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmApprovalOnline
    {
        public int ApprovalID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ContractMemberID { get; set; }
        public Nullable<long> ApprovalCode { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Diagnosis { get; set; }
        public string ICDCode { get; set; }
        public string Notes { get; set; }
        public string CardNumber { get; set; }
        public string ContractNum { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string Approvalmemo { get; set; }
        public int IssueUserID { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<System.DateTime> EditUserDate { get; set; }
        public Nullable<int> CancelUserID { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public int ChronicTemplateID { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public Nullable<bool> IsDeduct { get; set; }
        public Nullable<int> MemberShowStatus { get; set; }
    }
}
