//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmApprovalItemsOnline
    {
        public int ApprovalItemID { get; set; }
        public int ApprovalID { get; set; }
        public long ApprovalCode { get; set; }
        public string ServiceName { get; set; }
        public decimal ServiceQnt { get; set; }
        public int CLaimServiceID { get; set; }
        public string ServiceNote { get; set; }
        public int ApprovalCLaimServiceID { get; set; }
        public Nullable<int> ProviderCatId { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<decimal> Number_of_times_a_day { get; set; }
        public Nullable<decimal> Dosage_size { get; set; }
        public Nullable<decimal> Number_of_days { get; set; }
    }
}
