//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMBatchImportView
    {
        public string ContractNumber { get; set; }
        public Nullable<decimal> DueAmt { get; set; }
        public Nullable<decimal> MedicalDeductAmt { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> DeducatAmt { get; set; }
        public Nullable<decimal> ClaimedAmt { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public Nullable<long> BatchNumber { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string ClaimedServiceName { get; set; }
        public string فئة_الخدمة { get; set; }
        public string ServiceName { get; set; }
        public string ProviderName { get; set; }
        public string CustomerName { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public string ICD { get; set; }
        public int ContractMemberID { get; set; }
        public int ProviderID { get; set; }
        public int ClaimServiceID { get; set; }
    }
}
