//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMClaimsONLINE
    {
        public int ClaimID { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public Nullable<int> ContractMemberID { get; set; }
        public Nullable<System.DateTime> symptomsDate { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<int> ClaimServiceID { get; set; }
        public string Diagnosis { get; set; }
        public string ICDCode { get; set; }
        public Nullable<int> ClaimStatusID { get; set; }
        public Nullable<int> UserAddID { get; set; }
        public Nullable<int> UserApproveID { get; set; }
        public string ContractNum { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> ProviderCatID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string BranchName { get; set; }
        public string SecondDiagnosis { get; set; }
        public string SecondICDCode { get; set; }
        public string ThirdDiagnosis { get; set; }
        public string ThirdICDCode { get; set; }
    }
}
