//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMChronicBatch
    {
        public int ChronicBatchID { get; set; }
        public int ChronicTemplateID { get; set; }
        public System.DateTime IssueBatchDate { get; set; }
        public int IssueMonth { get; set; }
        public int IssueYear { get; set; }
        public int IssueUserID { get; set; }
        public System.DateTime IssueUserDate { get; set; }
    }
}
