//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMChronicMember
    {
        public int ChronicMemberID { get; set; }
        public int ContractMemberID { get; set; }
        public int ChronicTemplateID { get; set; }
        public int ProviderID { get; set; }
        public string ICDCode { get; set; }
        public long CardNumber { get; set; }
        public Nullable<int> BranchID { get; set; }
    }
}
