//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMClaimItem
    {
        public int ClaimItemID { get; set; }
        public int ClaimID { get; set; }
        public int ServiceID { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public decimal ServiceQnt { get; set; }
        public decimal ServiceUnitAmt { get; set; }
        public decimal ClaimedAmt { get; set; }
        public decimal DeductAmt { get; set; }
        public decimal DiscountAmt { get; set; }
        public decimal FDiscountAmt { get; set; }
        public decimal MedicalDeductAmt { get; set; }
        public decimal DueAmt { get; set; }
        public decimal RequestedAmt { get; set; }
        public decimal DifferenceAmt { get; set; }
        public string RejectNotes { get; set; }
        public bool IsSysEntry { get; set; }
        public int UserEntryID { get; set; }
        public System.DateTime UserEntryDate { get; set; }
        public bool UserApprove { get; set; }
        public int UserApproveID { get; set; }
        public string BatchNumber { get; set; }
        public long ClaimNum { get; set; }
        public decimal ServiceAmt { get; set; }
        public decimal ServiceDeductAmt { get; set; }
        public decimal ServiceDiscountAmt { get; set; }
        public decimal NetServiceAmt { get; set; }
        public int ClaimServiceID { get; set; }
        public decimal ServiceDiscountPer { get; set; }
        public bool IsCovered { get; set; }
        public bool IsImported { get; set; }
        public decimal NetPaymentAmt { get; set; }
        public decimal ReimbPer { get; set; }
        public decimal AuditDeductAmt { get; set; }
        public string AuditComments { get; set; }
        public bool IsOverCeiling { get; set; }
        public Nullable<decimal> Number_of_times_a_day { get; set; }
        public Nullable<decimal> Dosage_size { get; set; }
        public Nullable<decimal> Number_of_days { get; set; }
        public Nullable<System.DateTime> EndDate_Effective_Material { get; set; }
    }
}
