//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMClaimsItemsONLINE
    {
        public int ClaimItemID { get; set; }
        public int ClaimID { get; set; }
        public int ServiceID { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> ServiceQnt { get; set; }
        public Nullable<int> UserEntryID { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
        public Nullable<bool> UserApprove { get; set; }
        public Nullable<int> UserApproveID { get; set; }
        public long ClaimNum { get; set; }
        public int ClaimServiceID { get; set; }
        public bool IsCovered { get; set; }
        public bool IsImported { get; set; }
        public Nullable<int> ClaimItemStatusID { get; set; }
        public string Refuse_Note { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public Nullable<decimal> ServiceAmt { get; set; }
        public Nullable<decimal> RequestedPrice { get; set; }
        public Nullable<decimal> Number_of_times_a_day { get; set; }
        public Nullable<decimal> Dosage_size { get; set; }
        public Nullable<decimal> Number_of_days { get; set; }
    }
}
