//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMChronicMemberDrug
    {
        public int ChronicMemberDrugID { get; set; }
        public int ChronicMemberID { get; set; }
        public int MedDrugID { get; set; }
        public decimal NoOfUnits { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
        public string ICDCode { get; set; }
        public int ClaimServiceID { get; set; }
        public long CardNumber { get; set; }
        public int ChronicTemplateID { get; set; }
    }
}
