//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMComApproval
    {
        public int ApprovalID { get; set; }
        public int CustomerID { get; set; }
        public int ProviderID { get; set; }
        public Nullable<int> ContractMemberID { get; set; }
        public Nullable<long> ApprovalCode { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> ClaimServiceID { get; set; }
        public Nullable<decimal> ApprovalAmt { get; set; }
        public Nullable<decimal> DeductPer { get; set; }
        public Nullable<decimal> DeductAmt { get; set; }
        public string Diagnosis { get; set; }
        public string ICDCode { get; set; }
        public string Notes { get; set; }
        public string CardNumber { get; set; }
        public string CustomerCode { get; set; }
        public string ProviderCode { get; set; }
        public string ContractNum { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string Approvalmemo { get; set; }
        public int IssueUserID { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<System.DateTime> EditUserDate { get; set; }
        public Nullable<int> CancelUserID { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public int ChronicTemplateID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusNotes { get; set; }
        public string MemberName { get; set; }
    }
}
