//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMUtilizationRep
    {
        public decimal DueAmt { get; set; }
        public string CardNumber { get; set; }
        public string MemberName { get; set; }
        public string CustomerName { get; set; }
        public int CustomerID { get; set; }
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public int ClaimItemID { get; set; }
        public int ClaimID { get; set; }
        public string ContractNum { get; set; }
    }
}
