//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMView
    {
        public int ClaimID { get; set; }
        public int RecBatchID { get; set; }
        public long ClaimFormNum { get; set; }
        public int ContractMemberID { get; set; }
        public Nullable<System.DateTime> symptomsDate { get; set; }
        public System.DateTime ProcedureDate { get; set; }
        public int ClaimServiceID { get; set; }
        public string Diagnosis { get; set; }
        public string ICDCode { get; set; }
        public decimal TClaimAmt { get; set; }
        public decimal TDeductAmt { get; set; }
        public decimal TDiscountAmt { get; set; }
        public decimal TAClaimAmt { get; set; }
        public decimal TADeductAmt { get; set; }
        public decimal TDifferenceAmt { get; set; }
        public int ClaimStatusID { get; set; }
        public int UserAddID { get; set; }
        public int UserApproveID { get; set; }
        public decimal NetClaimedAmt { get; set; }
        public decimal TRequestedAmt { get; set; }
        public string BatchNumber { get; set; }
        public string ContractNum { get; set; }
        public string CardNumber { get; set; }
    }
}
