//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLTClient
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public bool CollectInvoice { get; set; }
        public bool CeilingOnNet { get; set; }
        public bool PayToProvider { get; set; }
    }
}
