//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public bool IsActive { get; set; }
        public int CustomerID { get; set; }
        public int PaymentPeriod { get; set; }
        public decimal TotalPermuimAmt { get; set; }
        public decimal AdminFeesAmt { get; set; }
        public decimal BrokerPer { get; set; }
        public decimal VATPer { get; set; }
        public int ContractTypeID { get; set; }
        public decimal AdditionFeesAmt { get; set; }
        public decimal PersonHumFund { get; set; }
        public decimal PersonPremuimCard { get; set; }
        public decimal PersonAccident { get; set; }
        public decimal TotalPreviousLoss { get; set; }
        public decimal DoctorFees { get; set; }
        public Nullable<decimal> PerUtilization { get; set; }
        public string ContractImage { get; set; }
        public string TaxcardImage { get; set; }
        public string CommercialRegisterImage { get; set; }
    }
}
