//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsTOBView
    {
        public string CustomerName { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public string PlanTypeName { get; set; }
        public int MembersInPlan { get; set; }
        public decimal AnnualCeiling { get; set; }
        public string ServiceName { get; set; }
        public decimal CeilingAmt { get; set; }
        public decimal DeductPer { get; set; }
        public Nullable<decimal> PremuimAmt { get; set; }
    }
}
