//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsWithPlansView
    {
        public int ContractID { get; set; }
        public string CustomerName { get; set; }
        public string ContractNumber { get; set; }
        public int PlanTypeID { get; set; }
        public string PlanTypeCode { get; set; }
    }
}
