//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractServiceCeiling
    {
        public int ServiceCeilingID { get; set; }
        public int ContractID { get; set; }
        public int ServiceID { get; set; }
        public int CeilingTypeID { get; set; }
        public decimal CeilingAmt { get; set; }
        public decimal DeductPer { get; set; }
        public decimal MemberLimitAmt { get; set; }
        public int MaxMemberInService { get; set; }
        public int PlanTypeID { get; set; }
        public decimal CustomerDeductPer { get; set; }
        public Nullable<decimal> CeilingAmtPerMonth { get; set; }
    }
}
