//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractPlanPermuim
    {
        public int ContractPermuimID { get; set; }
        public int ContractID { get; set; }
        public int PlanTypeID { get; set; }
        public int MembersInPlan { get; set; }
        public decimal MemberPermuimAmt { get; set; }
        public decimal GrossPremuimAmt { get; set; }
    }
}
