//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractPlanCeiling
    {
        public int PlanCeilingID { get; set; }
        public int ContractID { get; set; }
        public int PlanTypeID { get; set; }
        public decimal AnnualCeiling { get; set; }
        public int SessionID { get; set; }
        public int AccommodationID { get; set; }
        public int WaitingPeriodID { get; set; }
        public int MembersInPlan { get; set; }
        public int QuotationCatID { get; set; }
        public int NetWorkTypeID { get; set; }
        public Nullable<int> ServiceName_repeatTime { get; set; }
    }
}
