//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractReimboldData
    {
        public int ContractReimbID { get; set; }
        public int CustomerID { get; set; }
        public int ContractID { get; set; }
        public int HosProviderID { get; set; }
        public int HosContractID { get; set; }
        public int PhysProviderID { get; set; }
        public int PhysContractID { get; set; }
        public int LabProviderID { get; set; }
        public int LabContractID { get; set; }
        public int ScanProviderID { get; set; }
        public int ScanContractID { get; set; }
        public int MedProviderID { get; set; }
        public int MedContractID { get; set; }
    }
}
