//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractCondition
    {
        public int ContractConID { get; set; }
        public int QuotationID { get; set; }
        public string ConNameEn { get; set; }
        public string ConNameAr { get; set; }
        public string ContractConEn { get; set; }
        public string ContractConAr { get; set; }
    }
}
