//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMLogData
    {
        public int CRMLogID { get; set; }
        public int CRMLogActionTypeID { get; set; }
        public int UserID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string CustomerName { get; set; }
    }
}
