//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCensu
    {
        public int CustomerCensusID { get; set; }
        public int CustomerID { get; set; }
        public int AgeBraketID { get; set; }
        public int PlanTypeID { get; set; }
        public int TotalMembers { get; set; }
        public int TemplateID { get; set; }
    }
}
