//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerClaimsInquiry2
    {
        public int ClaimID { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public string Diagnosis { get; set; }
        public string ICDCode { get; set; }
        public Nullable<decimal> TotalClaimedAmt { get; set; }
        public Nullable<decimal> TotalDeductAmt { get; set; }
        public Nullable<decimal> TotalDiscountAmt { get; set; }
        public Nullable<decimal> TotalFDiscountAmt { get; set; }
        public Nullable<decimal> TotalMedical_Deduct { get; set; }
        public Nullable<decimal> TotalDueAmt { get; set; }
        public string CardNumber { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<int> RecBatchID { get; set; }
        public string MemberName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<long> BatchNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> ContractID { get; set; }
    }
}
