//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLoginData
    {
        public int CustomerLoginID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContract { get; set; }
        public string CusomerUsername { get; set; }
        public string CustomerPassword { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LoginEnterId { get; set; }
    }
}
