//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContactData
    {
        public int ContactID { get; set; }
        public int CustomerID { get; set; }
        public string ContactName { get; set; }
        public string JobTitle { get; set; }
        public string PhoneNum { get; set; }
        public string PhoneExtention { get; set; }
        public string MobileNum { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNum2 { get; set; }
    }
}
