//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerData
    {
        public int CustomerID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> BusinessFieldID { get; set; }
        public string LandLine1 { get; set; }
        public string LandLine2 { get; set; }
        public string LandLine3 { get; set; }
        public string LandLine4 { get; set; }
        public string FaxNum { get; set; }
        public string EmailAdd { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<bool> IsInsured { get; set; }
        public string InsuranceCompany { get; set; }
        public Nullable<int> SubStatusID { get; set; }
        public Nullable<bool> Islinked { get; set; }
        public Nullable<int> CCGroupID { get; set; }
        public string CompanySize { get; set; }
        public Nullable<int> SubBrokerID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CustomerCatID { get; set; }
        public Nullable<int> CustomerSubCatID { get; set; }
        public int InsuranceCompanyID { get; set; }
    }
}
