//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class EatingData
    {
        public int EatingID { get; set; }
        public bool MeatEater { get; set; }
        public bool Pescatarian { get; set; }
        public bool Vegetarian { get; set; }
        public bool LactoOvoVegetarian { get; set; }
        public bool LactoVegetarian { get; set; }
        public bool OvoVegetarian { get; set; }
        public bool Vegan { get; set; }
    }
}
