//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ethnicitySubGroupData
    {
        public int ethnicitySubGroupID { get; set; }
        public string ethnicitySubGroupName { get; set; }
        public int ethnicityMainGroupID { get; set; }
    }
}
