//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class familyHistoryData
    {
        public int familyHistoryID { get; set; }
        public bool Heartdisease { get; set; }
        public bool Diabetes { get; set; }
        public bool Chronicbronchitis { get; set; }
        public bool Dementia { get; set; }
        public bool Stroke { get; set; }
        public bool Noneoftheabove { get; set; }
    }
}
