//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetClaimSum
    {
        public int ClaimID { get; set; }
        public Nullable<decimal> TDueAmt { get; set; }
        public Nullable<decimal> TRequestedAmt { get; set; }
        public Nullable<decimal> TDifferenceAmt { get; set; }
        public Nullable<decimal> TClaimedAmt { get; set; }
        public Nullable<decimal> TDeductAmt { get; set; }
        public Nullable<decimal> TDiscountAmt { get; set; }
        public Nullable<decimal> TMedicalDeduct { get; set; }
        public Nullable<decimal> TNetPaymentAmt { get; set; }
    }
}
