//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Go_RECLAIM
    {
        public decimal SA_RCODE { get; set; }
        public string SA_CCODE { get; set; }
        public System.DateTime SA_RDATE { get; set; }
        public Nullable<double> SA_RVALUE { get; set; }
        public Nullable<double> SA_RSALTAX { get; set; }
        public Nullable<double> SA_RADDTAX { get; set; }
        public Nullable<double> SA_RPAIDCASH { get; set; }
        public Nullable<double> SA_RPAIDCHECKS { get; set; }
        public Nullable<double> SA_RCOLLECTCASH { get; set; }
        public Nullable<double> SA_RCOLLECTCHECKS { get; set; }
        public Nullable<double> SA_RRETURN { get; set; }
        public string SA_RSTATUS { get; set; }
        public string SA_RNOTES { get; set; }
        public string ISSENT { get; set; }
        public string SA_OPEN { get; set; }
        public Nullable<double> SA_DISCOUNT { get; set; }
        public Nullable<double> SA_CASHDISC { get; set; }
        public Nullable<double> EXT_PAY { get; set; }
        public Nullable<double> ADJ_PAY { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> HAND_ID { get; set; }
        public string SA_COSTCENTER { get; set; }
        public string LAST_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATE_FROM { get; set; }
        public string USER_SERIAL { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<double> REVISION_DISCOUNT { get; set; }
        public Nullable<double> MEDICAL_DISCOUNT { get; set; }
        public string MEDICALLY_REVISED { get; set; }
        public string MEDICALLY_REVISED_BY { get; set; }
        public string MEDICALLY_REVISED_FROM { get; set; }
        public Nullable<System.DateTime> MEDICALLY_REVISED_DATE { get; set; }
        public string PIC_PATH { get; set; }
        public Nullable<double> corrected_value { get; set; }
        public Nullable<double> diff_value { get; set; }
        public string diff_reason { get; set; }
        public string Pricing_REVISED_BY { get; set; }
        public string Pricing_REVISED_FROM { get; set; }
        public Nullable<System.DateTime> Pricing_REVISED_DATE { get; set; }
        public string Pricing_REVISED { get; set; }
        public string REVISED_BY { get; set; }
        public string REVISED_FROM { get; set; }
        public Nullable<System.DateTime> REVISED_DATE { get; set; }
        public Nullable<double> REVISED_value { get; set; }
        public Nullable<double> net_recieved { get; set; }
        public string EXT_CODE { get; set; }
        public Nullable<int> recieved_invoices_count { get; set; }
        public Nullable<decimal> SA_Parent_RCODE { get; set; }
        public string reimbursement_info { get; set; }
    }
}
