//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportClaim
    {
        public Nullable<long> ClaimFormNum { get; set; }
        public Nullable<int> ContractMemberID { get; set; }
        public Nullable<System.DateTime> symptomsDate { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<int> ClaimServiceID { get; set; }
        public Nullable<decimal> TClaimAmt { get; set; }
        public Nullable<decimal> TDiscountAmt { get; set; }
        public Nullable<int> TAClaimAmt { get; set; }
        public Nullable<decimal> TMedicalDeductAmt { get; set; }
        public Nullable<int> ClaimStatusID { get; set; }
        public Nullable<int> UserAddID { get; set; }
        public Nullable<int> UserApproveID { get; set; }
        public Nullable<decimal> TRequestedAmt { get; set; }
        public string BatchNumber { get; set; }
        public string ContractNum { get; set; }
        public string CardNumber { get; set; }
        public int RecBatchID { get; set; }
        public string ICDCode { get; set; }
        public Nullable<decimal> DeductAmt { get; set; }
    }
}
