//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImprovementsData
    {
        public int ImprovementsID { get; set; }
        public bool ReducingAlcoholIntake { get; set; }
        public bool StopSmoking { get; set; }
        public bool IncreaseExercise { get; set; }
        public bool ImproveSleep { get; set; }
        public bool HealthierDiet { get; set; }
        public bool ReduceCaffeineIntake { get; set; }
        public bool IncreaseWaterIntake { get; set; }
        public bool ImproveMood { get; set; }
        public bool ReduceStressAnxiety { get; set; }
        public bool Looseweight { get; set; }
        public bool Increasestrength { get; set; }
        public bool Improveflexibility { get; set; }
        public bool Noneoftheabove { get; set; }
    }
}
