//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompanyData
    {
        public int InsuranceCompanyID { get; set; }
        public string InsuranceCompanyName { get; set; }
        public string InsuranceCompanyCode { get; set; }
        public string LandLine1 { get; set; }
        public string LandLine2 { get; set; }
        public string LandLine3 { get; set; }
        public string LandLine4 { get; set; }
        public string FaxNum { get; set; }
        public string EmailAdd { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Notes { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
