//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlarityQuestionData
    {
        public int KlarityQuestionID { get; set; }
        public int KlarityUserID { get; set; }
        public int SexTypeID { get; set; }
        public decimal UserWeight { get; set; }
        public decimal UserHeight { get; set; }
        public int ethnicitySubGroupID { get; set; }
        public int familyHistoryID { get; set; }
        public int PersonhavediseaseID { get; set; }
        public string SystolicBlood { get; set; }
        public string diastolicBlood { get; set; }
        public string RestingHeartRate { get; set; }
        public int SmokingStatusID { get; set; }
        public int SleepHoursIntervalID { get; set; }
        public int ModerateIntensityActivityMinutesID { get; set; }
        public int vigorousIntensityActivityMinutesID { get; set; }
        public int EatingID { get; set; }
        public string Eating_Meat { get; set; }
        public string Eating_oilyfish { get; set; }
        public int FreshFruit_PeicesID { get; set; }
        public int Vegetables_PeicesID { get; set; }
        public int CookedVegetables_PeicesID1 { get; set; }
        public int Alcohol_DrinkID { get; set; }
        public decimal WaterGlasses_DrinkID { get; set; }
        public int HappyHealthID { get; set; }
        public int ImprovementsID { get; set; }
    }
}
