//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class leadsTest
    {
        public Nullable<double> C_ { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> BusinessFieldID { get; set; }
        public string landLine1 { get; set; }
        public string Address { get; set; }
        public string EmailAdd { get; set; }
        public string FaxNum { get; set; }
        public string landLine2 { get; set; }
        public string Notes { get; set; }
    }
}
