//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public int LogID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> LogTypeID { get; set; }
        public int LogActionID { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ContractMemberID { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<System.DateTime> DeactiveDate { get; set; }
        public Nullable<int> MemberActivityStatusID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ContractReimbID { get; set; }
        public Nullable<bool> IsActiveContract { get; set; }
    }
}
