//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LQBatchPayment
    {
        public string BatchNumber { get; set; }
        public System.DateTime RecDate { get; set; }
        public decimal PaymentAmt { get; set; }
        public decimal AdminFeesAmt { get; set; }
        public decimal EarlyPaymentAmt { get; set; }
        public decimal AdditionDiscountAmt { get; set; }
        public decimal DeductableAmt { get; set; }
        public decimal NetPaymentAmt { get; set; }
        public decimal WHTaxAmt { get; set; }
        public decimal DuePaymentAmt { get; set; }
        public int PaymentID { get; set; }
        public string UserName { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string PaymentStatusName { get; set; }
    }
}
