//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LQBatchPaymentStatu
    {
        public string ProviderName { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmt { get; set; }
        public string PaymentMethodName { get; set; }
        public string BankAccNumber { get; set; }
        public string BankName { get; set; }
        public string BeneficiaryName { get; set; }
        public string BenBankName { get; set; }
        public string BenAccNumber { get; set; }
        public string BatchStatusName { get; set; }
        public Nullable<int> PayamentID { get; set; }
        public Nullable<decimal> ClaimTotalAmt { get; set; }
        public Nullable<decimal> Expr2 { get; set; }
        public Nullable<decimal> DueNetPaymentAmt { get; set; }
        public string Paymentmethod { get; set; }
        public Nullable<decimal> TotalAudit { get; set; }
        public Nullable<decimal> TotalDifference { get; set; }
        public Nullable<decimal> TotalMedical { get; set; }
        public Nullable<decimal> WHTaxAmt { get; set; }
        public Nullable<decimal> AdminFeesAmt { get; set; }
        public Nullable<decimal> RecBatchAmt { get; set; }
        public int Expr1 { get; set; }
        public string ProviderCatName { get; set; }
    }
}
