//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LQClaimItem
    {
        public string CustomerName { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime MemberBirthDate { get; set; }
        public string PlanTypeName { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public Nullable<System.DateTime> DeActiveDate { get; set; }
        public int MemberActivityStatusID { get; set; }
        public string NetWorkType { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ServiceName { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public string ProviderName { get; set; }
        public string ProviderCatName { get; set; }
        public decimal ClaimedAmt { get; set; }
        public decimal DeductAmt { get; set; }
        public decimal DiscountAmt { get; set; }
        public decimal MedicalDeductAmt { get; set; }
        public decimal DueAmt { get; set; }
        public string ICDCode { get; set; }
        public string Diagnosis { get; set; }
        public int CustomerID { get; set; }
        public string ServiceItemName { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
