//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LQMemberAddDelete
    {
        public int PlanTypeID { get; set; }
        public int ContractID { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public Nullable<System.DateTime> DeActiveDate { get; set; }
        public Nullable<int> UtilizedDays { get; set; }
        public decimal MemberPermuimAmt { get; set; }
        public Nullable<decimal> PremuimDayAmt { get; set; }
        public Nullable<decimal> DebitAmt { get; set; }
        public Nullable<decimal> CreditAmt { get; set; }
    }
}
