//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LQPayment
    {
        public int PayamentID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmt { get; set; }
        public string PaymentMethodName { get; set; }
        public string BankName { get; set; }
        public string BankAccNumber { get; set; }
        public string BenBankName { get; set; }
        public string BenAccNumber { get; set; }
        public string UserIssue { get; set; }
        public string UserCancel { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public bool IsActive { get; set; }
    }
}
