//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LQReimBatch
    {
        public Nullable<System.DateTime> RecDate { get; set; }
        public string BatchNumber { get; set; }
        public string CustomerName { get; set; }
        public string CardNumber { get; set; }
        public string MemberName { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<decimal> TRequestedAmt { get; set; }
        public Nullable<decimal> TClaimAmt { get; set; }
        public Nullable<decimal> TDeductAmt { get; set; }
        public Nullable<decimal> TDiscountAmt { get; set; }
        public Nullable<decimal> TMedicalDeductAmt { get; set; }
        public Nullable<decimal> NetClaimedAmt { get; set; }
        public string BatchStatusName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmt { get; set; }
        public string PaymentDocNum { get; set; }
        public string PaymentMethodName { get; set; }
        public string BeneficiaryName { get; set; }
        public string BenBankName { get; set; }
        public string BenAccNumber { get; set; }
        public Nullable<int> PayamentID { get; set; }
    }
}
