//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LQTax41
    {
        public string TaxCardNum { get; set; }
        public string TaxFileNum { get; set; }
        public string TaxPayer { get; set; }
        public string ProviderName { get; set; }
        public string ProviderAddress { get; set; }
        public string TaxDepartmentName { get; set; }
        public string TranseferNotes { get; set; }
        public System.DateTime RecDate { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public string TaxType { get; set; }
        public decimal PaymentAmt { get; set; }
        public decimal NetPaymentAmt { get; set; }
        public decimal WHTaxAmt { get; set; }
        public string BatchNumber { get; set; }
    }
}
