//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LQUserCLMEntry
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int ClaimID { get; set; }
        public Nullable<long> ClaimFormNumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> TotalItems { get; set; }
    }
}
