//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUAgeBraket
    {
        public int TemplateID { get; set; }
        public int AgeBraketID { get; set; }
        public int FromAge { get; set; }
        public int ToAge { get; set; }
        public decimal AgeFactor { get; set; }
        public int AgeGroupID { get; set; }
    }
}
