//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUAppSerial
    {
        public int SerNoID { get; set; }
        public long BatchSerialNum { get; set; }
        public long ReImpSerialNum { get; set; }
        public long ApprovalSerialNum { get; set; }
        public long ChronicSerialNum { get; set; }
        public long ClmReimbSerialNum { get; set; }
        public long ComApprovalSerialNum { get; set; }
        public long InvoiceSerialNum { get; set; }
        public long InvoiceAltSerialNum { get; set; }
    }
}
