//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUCeilingAmount
    {
        public int TemplateID { get; set; }
        public int CeilingID { get; set; }
        public decimal CeilingAmt { get; set; }
        public decimal CeilingPer { get; set; }
    }
}
