//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUFixedExpen
    {
        public int FixedExpensID { get; set; }
        public int TemplateID { get; set; }
        public string FixedExpensName { get; set; }
        public decimal FixedExpensValue { get; set; }
        public bool IsFixedPercentage { get; set; }
    }
}
