//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUOrgan
    {
        public int TemplateID { get; set; }
        public int OrganID { get; set; }
        public int FromMember { get; set; }
        public int ToMember { get; set; }
        public decimal OrganAmt { get; set; }
    }
}
