//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUTemplate
    {
        public int TemplateID { get; set; }
        public string TemplateName { get; set; }
        public decimal BasicAnnualCeiling { get; set; }
        public decimal BasicPremuim { get; set; }
        public int T2ActiveMember { get; set; }
        public decimal T2BasicPremuim { get; set; }
        public decimal BasicFundAmt { get; set; }
    }
}
