//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUTemplateService
    {
        public int TemplateServiceID { get; set; }
        public int TemplateID { get; set; }
        public int ServiceID { get; set; }
        public bool IsDefault { get; set; }
        public bool AllowAddCeiling { get; set; }
        public bool AllowDiscount { get; set; }
        public decimal PremiumAmt { get; set; }
        public decimal AddFactorAmt { get; set; }
        public decimal AddFactorPer { get; set; }
        public decimal ExtraCeilingAmt { get; set; }
        public decimal ExtraPremiumAmt { get; set; }
        public bool MaxCeiling { get; set; }
        public int MaxServiceID { get; set; }
    }
}
