//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistoryMember
    {
        public string CustomerName { get; set; }
        public string MemberName { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime MemberBirthDate { get; set; }
        public string MemberActivityStatusName { get; set; }
        public string SexType { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public string ServiceName { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string ServiceItemName { get; set; }
        public decimal ServiceQnt { get; set; }
        public string ServiceCode { get; set; }
        public int ClaimID { get; set; }
        public string Expr5 { get; set; }
        public Nullable<decimal> NetClaimedAmt { get; set; }
    }
}
