//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberUTView
    {
        public Nullable<int> ContractMemberID { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public string ServiceName { get; set; }
        public decimal ServiceQnt { get; set; }
        public decimal DueAmt { get; set; }
        public string CardNumber { get; set; }
    }
}
