//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberClaimImage
    {
        public int MemberClaimImageID { get; set; }
        public string CardNumber { get; set; }
        public string ClaimFormImage { get; set; }
        public int MemberClaimImageStatus { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<long> ApprovalNumber { get; set; }
    }
}
