//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messanger
    {
        public int MessageID { get; set; }
        public int ProviderID { get; set; }
        public int BranchID { get; set; }
        public int ProviderUserID { get; set; }
        public string ProviderName { get; set; }
        public string BranchName { get; set; }
        public int CMCUserID { get; set; }
        public string CMCName { get; set; }
        public string Message { get; set; }
        public System.DateTime MessageDateTime { get; set; }
        public bool IsProvider { get; set; }
        public bool IsCMC { get; set; }
        public bool ProviderShow { get; set; }
        public bool CMCShow { get; set; }
    }
}
