//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferPaymentMethod
    {
        public int OfferPaymentMethodID { get; set; }
        public string PaymentMethodAr1 { get; set; }
        public string PaymentMethodEn1 { get; set; }
        public string PaymentMethodAr2 { get; set; }
        public string PaymentMethodEn2 { get; set; }
        public string PaymentMethodName { get; set; }
    }
}
