//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferView
    {
        public string CustomerName { get; set; }
        public decimal OrgenAmt { get; set; }
        public decimal BasicFundAmt { get; set; }
        public decimal TotalNetPermuim { get; set; }
        public decimal AdministrativeFee { get; set; }
        public decimal GrossPremuim { get; set; }
        public System.DateTime OfferDate { get; set; }
        public int OfferGroupID { get; set; }
        public string OfferGroupNameAr { get; set; }
        public string OfferGroupNameEn { get; set; }
        public string OfferTypeName { get; set; }
        public string PlanA { get; set; }
        public string PlanB { get; set; }
        public string PlanC { get; set; }
        public string PlanD { get; set; }
        public string PlanE { get; set; }
        public string OfferTemplateNameAr { get; set; }
        public string OfferTemplateNameEn { get; set; }
        public int MembersPlanA { get; set; }
        public int MembersPlanB { get; set; }
        public int MembersPlanC { get; set; }
        public int MembersPlanD { get; set; }
        public decimal CeilingPlanA { get; set; }
        public decimal CeilingPlanB { get; set; }
        public decimal CeilingPlanC { get; set; }
        public decimal CeilingPlanD { get; set; }
        public decimal PermiumPlanA { get; set; }
        public decimal PermiumPlanB { get; set; }
        public decimal PermiumPlanC { get; set; }
        public decimal PermiumPlanD { get; set; }
        public decimal TPermiumPlanA { get; set; }
        public decimal TPermiumPlanB { get; set; }
        public decimal TPermiumPlanC { get; set; }
        public decimal TPermiumPlanD { get; set; }
    }
}
