//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferFact
    {
        public string TitleEn { get; set; }
        public string DescriptionEn { get; set; }
        public string TitleAr { get; set; }
        public string DescriptionAr { get; set; }
    }
}
