//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferUPlan
    {
        public int PlanOfferID { get; set; }
        public int OfferID { get; set; }
        public int OfferTypeID { get; set; }
        public int OfferGroupID { get; set; }
        public int OfferTemplateID { get; set; }
        public string PlanA { get; set; }
        public string PlanB { get; set; }
        public string PlanC { get; set; }
        public string PlanD { get; set; }
        public string PlanE { get; set; }
        public string PlanF { get; set; }
    }
}
