//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferFinanceIn
    {
        public int OfferFinanceID { get; set; }
        public int OfferID { get; set; }
        public int MembersPlanInA { get; set; }
        public int MembersPlanInB { get; set; }
        public int MembersPlanInC { get; set; }
        public int MembersPlanInD { get; set; }
        public int MembersPlanInE { get; set; }
        public int MembersPlanInF { get; set; }
        public decimal CeilingPlanInA { get; set; }
        public decimal CeilingPlanInB { get; set; }
        public decimal CeilingPlanInC { get; set; }
        public decimal CeilingPlanInD { get; set; }
        public decimal CeilingPlanInE { get; set; }
        public decimal CeilingPlanInF { get; set; }
        public decimal PermiumPlanInA { get; set; }
        public decimal PermiumPlanInB { get; set; }
        public decimal PermiumPlanInC { get; set; }
        public decimal PermiumPlanInD { get; set; }
        public decimal PermiumPlanInE { get; set; }
        public decimal PermiumPlanInF { get; set; }
        public decimal TPermiumPlanInA { get; set; }
        public decimal TPermiumPlanInB { get; set; }
        public decimal TPermiumPlanInC { get; set; }
        public decimal TPermiumPlanInD { get; set; }
        public decimal TPermiumPlanInE { get; set; }
        public decimal TPermiumPlanInF { get; set; }
    }
}
