//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferLTemplate
    {
        public int OfferTemplateID { get; set; }
        public string OfferTemplateNameAr { get; set; }
        public string OfferTemplateNameEn { get; set; }
        public int OfferGroupID { get; set; }
        public bool IsActive { get; set; }
        public bool Unlimited { get; set; }
        public bool IsTotalMember { get; set; }
        public bool IsBule { get; set; }
        public bool IsActiveU { get; set; }
        public bool IsActiveC { get; set; }
        public Nullable<int> DesplaySerial { get; set; }
    }
}
