//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferCondition
    {
        public int OfferConDefID { get; set; }
        public string OfferNameEn { get; set; }
        public string OfferNameAr { get; set; }
        public string OfferConEn { get; set; }
        public string OfferConAr { get; set; }
    }
}
