//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferSummary
    {
        public int OfferSummaryID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<int> TotEmpNum { get; set; }
        public Nullable<decimal> AvgPrem { get; set; }
        public Nullable<decimal> EstPrem { get; set; }
        public int OfferNum { get; set; }
    }
}
