//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferUFinance
    {
        public int OfferFinanceID { get; set; }
        public int OfferID { get; set; }
        public int MembersPlanA { get; set; }
        public int MembersPlanB { get; set; }
        public int MembersPlanC { get; set; }
        public int MembersPlanD { get; set; }
        public int MembersPlanE { get; set; }
        public int MembersPlanF { get; set; }
        public decimal CeilingPlanA { get; set; }
        public decimal CeilingPlanB { get; set; }
        public decimal CeilingPlanC { get; set; }
        public decimal CeilingPlanD { get; set; }
        public decimal CeilingPlanE { get; set; }
        public decimal CeilingPlanF { get; set; }
        public decimal PermiumPlanA { get; set; }
        public decimal PermiumPlanB { get; set; }
        public decimal PermiumPlanC { get; set; }
        public decimal PermiumPlanD { get; set; }
        public decimal PermiumPlanE { get; set; }
        public decimal PermiumPlanF { get; set; }
        public decimal TPermiumPlanA { get; set; }
        public decimal TPermiumPlanB { get; set; }
        public decimal TPermiumPlanC { get; set; }
        public decimal TPermiumPlanD { get; set; }
        public decimal TPermiumPlanE { get; set; }
        public decimal TPermiumPlanF { get; set; }
        public string NetWorkPlanA { get; set; }
        public string NetWorkPlanB { get; set; }
        public string NetWorkPlanC { get; set; }
        public string NetWorkPlanD { get; set; }
        public string NetWorkPlanE { get; set; }
        public string NetWorkPlanF { get; set; }
    }
}
