//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentView
    {
        public int PayamentID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string BankAccName { get; set; }
        public string ProviderName { get; set; }
        public string BeneficiaryName { get; set; }
        public string BenAccNumber { get; set; }
        public string BenBankName { get; set; }
        public string Comments { get; set; }
        public int RecBatchID { get; set; }
        public System.DateTime RecDate { get; set; }
        public string PaymentMethodName { get; set; }
        public decimal PaymentAmt { get; set; }
        public decimal AdminFeesAmt { get; set; }
        public decimal EarlyPaymentAmt { get; set; }
        public decimal AdditionDiscountAmt { get; set; }
        public decimal NetPaymentAmt { get; set; }
        public decimal WHTaxAmt { get; set; }
        public decimal DuePaymentAmt { get; set; }
        public decimal NetPayAmt { get; set; }
        public string PaymentInWord { get; set; }
    }
}
