//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonhavediseaseData
    {
        public int PersonhavediseaseID { get; set; }
        public bool HighBloodPressure { get; set; }
        public bool HeartAttack { get; set; }
        public bool Stroke { get; set; }
        public bool Angina { get; set; }
        public bool Emphysema_ChronicBronchitis { get; set; }
        public bool Diabetes { get; set; }
        public bool Cancer { get; set; }
        public bool Asthma { get; set; }
        public bool Dementia { get; set; }
        public bool Noneoftheabove { get; set; }
    }
}
