//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiecesData
    {
        public int PiecesID { get; set; }
        public string PiecesName { get; set; }
    }
}
