//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderUserData
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsLockedOut { get; set; }
        public bool IsFirstLogin { get; set; }
        public int InvalidPasswordAttempts { get; set; }
        public bool IsAdmin { get; set; }
        public int UserTypeID { get; set; }
        public int UserTypeCustomerID { get; set; }
        public string UserImage { get; set; }
        public int ProviderID { get; set; }
        public int BranchID { get; set; }
        public bool ProviderAdmin { get; set; }
    }
}
