//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidersInquirey
    {
        public string ProviderName { get; set; }
        public string ProviderCode { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Contact3 { get; set; }
        public string ContactEmail1 { get; set; }
        public Nullable<int> ProviderSubCatID { get; set; }
        public string ProviderAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BranchNum { get; set; }
        public string ProviderNotes { get; set; }
        public decimal Price { get; set; }
        public string ServiceName { get; set; }
        public int ServiceCatID { get; set; }
        public decimal DiscountPerc { get; set; }
    }
}
