//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTLPricingPlan
    {
        public int PricingPlanID { get; set; }
        public string PlanName { get; set; }
        public string Coverage { get; set; }
        public string MembersNumber { get; set; }
        public string CoverageEligibility { get; set; }
        public string TotalAnnualPerPerson { get; set; }
        public string InPatientServiceAmt { get; set; }
        public string InPatientAcute { get; set; }
        public string InPatientPreEx { get; set; }
        public string OutPatientServiceAmt { get; set; }
        public string AmbAcute { get; set; }
        public string AmbPreEx { get; set; }
        public string Medication { get; set; }
        public string MedicationPreEx { get; set; }
        public string Physiotherapy { get; set; }
        public string Maternity { get; set; }
        public string Dental { get; set; }
        public string Vision { get; set; }
        public string OrganTransplantFund { get; set; }
        public string ProsthesisFund { get; set; }
        public string HumanitarianFund { get; set; }
        public string PlanA { get; set; }
        public string PlanADesc { get; set; }
        public string PlanAPrice { get; set; }
        public string PlanB { get; set; }
        public string PlanBDesc { get; set; }
        public string PlanBPice { get; set; }
        public string PlanC { get; set; }
        public string PlanCDesc { get; set; }
        public string PlanCPrice { get; set; }
    }
}
