//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVClaimsBookView
    {
        public string ProviderName { get; set; }
        public string ProviderCode { get; set; }
        public int BookNum { get; set; }
        public int FromSerial { get; set; }
        public int ToSerial { get; set; }
        public System.DateTime ActiveDate { get; set; }
    }
}
