//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVClaimsBook
    {
        public int BookID { get; set; }
        public int FromSerial { get; set; }
        public int ToSerial { get; set; }
        public int CurrentSerial { get; set; }
        public bool IsActive { get; set; }
    }
}
