//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVMedData
    {
        public int MedDrugID { get; set; }
        public string MedDrugName { get; set; }
        public string DosageForm { get; set; }
        public decimal Price { get; set; }
        public int MedUnitID { get; set; }
        public decimal UnitsNum { get; set; }
        public int MedCatID { get; set; }
        public string MedDrugCode { get; set; }
        public bool IsImported { get; set; }
        public bool IsCoverd { get; set; }
        public string MedDrugName_AR { get; set; }
        public string Effective_Material { get; set; }
        public string Classification { get; set; }
        public Nullable<int> Collection_ID { get; set; }
    }
}
