//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVMedCat
    {
        public int MedCatID { get; set; }
        public string MedCatName { get; set; }
        public bool IsCovered { get; set; }
        public bool IsImported { get; set; }
    }
}
