//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVMedException
    {
        public int PVMedExceptionID { get; set; }
        public int ProviderContractID { get; set; }
        public int ProviderID { get; set; }
        public int MedDrugID { get; set; }
        public string MedDrugName { get; set; }
        public decimal DiscountPer { get; set; }
    }
}
