//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVProviderData
    {
        public int ProviderID { get; set; }
        public string ProviderCode { get; set; }
        public string ProviderName { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Contact3 { get; set; }
        public string ContactEmail1 { get; set; }
        public Nullable<int> ProviderSubCatID { get; set; }
        public Nullable<int> BranchNum { get; set; }
        public string ProviderStatus { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string ProviderAddress { get; set; }
        public Nullable<int> PaymentPeriod { get; set; }
        public string beneficiaryName { get; set; }
        public string BankAccNum { get; set; }
        public string BankName { get; set; }
        public string TaxPayer { get; set; }
        public string TaxDepartmentName { get; set; }
        public string TaxFileNum { get; set; }
        public string TaxCardNum { get; set; }
        public string ComRegisterNum { get; set; }
        public string WebSiteName { get; set; }
        public string EmailAddress { get; set; }
        public string NetworkCat { get; set; }
        public string WorkingTimes { get; set; }
        public Nullable<int> ProviderCatID { get; set; }
        public string ContactEmail2 { get; set; }
        public string ContactEmail3 { get; set; }
        public string ContactPhone1 { get; set; }
        public string ContactPhone2 { get; set; }
        public string ContactPhone3 { get; set; }
        public string ProviderNotes { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ProviderNumber { get; set; }
        public string ProviderNameEn { get; set; }
        public string ProviderAddressEn { get; set; }
        public string WorkingHoursEn { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string LocationURL { get; set; }
        public bool IsCovid { get; set; }
        public Nullable<bool> IsWellness { get; set; }
        public string QRcodePath { get; set; }
    }
}
