//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PvServicePricingView2
    {
        public int ServicePricingID { get; set; }
        public int ServiceID { get; set; }
        public int ProviderID { get; set; }
        public int ServiceCatID { get; set; }
        public bool IsAvilable { get; set; }
        public decimal Price { get; set; }
        public decimal DiscountPerc { get; set; }
        public decimal DiscountVal { get; set; }
        public string Comments { get; set; }
        public string Notes { get; set; }
        public int ProviderContractID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceCode { get; set; }
        public string NamePrice { get; set; }
    }
}
