//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVTemplatePricing
    {
        public int ServicePricingID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> ServiceCatID { get; set; }
        public Nullable<bool> IsAvilable { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountPerc { get; set; }
        public Nullable<decimal> DiscountVal { get; set; }
        public string Comments { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ProviderContractID { get; set; }
        public int TemplateID { get; set; }
    }
}
