//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationTob
    {
        public int TobID { get; set; }
        public int QuotationID { get; set; }
        public int AgeBraketID { get; set; }
        public int CensusID { get; set; }
        public decimal RiskPremuim { get; set; }
        public decimal Maternity { get; set; }
        public decimal Dental { get; set; }
        public decimal Vision { get; set; }
        public decimal TotalPremuim { get; set; }
        public decimal GroupDiscount { get; set; }
        public decimal TPA { get; set; }
        public decimal InsCoProfit { get; set; }
        public decimal OverHead { get; set; }
        public decimal FundOver { get; set; }
        public decimal HumanFund { get; set; }
        public decimal TotalNetPremuim { get; set; }
        public decimal BrokerCommission { get; set; }
        public decimal TotalPremuimPerson { get; set; }
        public decimal TotalPremuimGroup { get; set; }
        public int PlanTypeID { get; set; }
        public int OfferTypeID { get; set; }
        public decimal VAT { get; set; }
        public decimal FixedAmt { get; set; }
    }
}
