//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public int QuotationID { get; set; }
        public int CustomerID { get; set; }
        public int PlanTypeID { get; set; }
        public int TemplateID { get; set; }
        public int QuotationStatus { get; set; }
        public int TotalMembers { get; set; }
        public int AccommodationTypeID { get; set; }
        public int IssueBy { get; set; }
        public int ApproveBy { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime StampDate { get; set; }
        public string QuotationName { get; set; }
        public bool AllowT2 { get; set; }
        public decimal LossPreYear { get; set; }
        public decimal PoolAmt { get; set; }
        public bool IsActive { get; set; }
        public int StatusId { get; set; }
        public string Comment { get; set; }
        public decimal PremiumCardAmt { get; set; }
        public string PoolConditions { get; set; }
        public decimal FixedAmt { get; set; }
        public string PoolConditionsEn { get; set; }
    }
}
