//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationRep
    {
        public string PlanTypeName { get; set; }
        public string AgeGroup { get; set; }
        public int CensusTotalNum { get; set; }
        public string CustomerName { get; set; }
        public decimal AnnualCeiling { get; set; }
        public System.DateTime IssueDate { get; set; }
        public decimal RiskPremuim { get; set; }
        public decimal Maternity { get; set; }
        public decimal Dental { get; set; }
        public decimal Vision { get; set; }
        public decimal TotalPremuim { get; set; }
        public decimal GroupDiscount { get; set; }
        public decimal TPA { get; set; }
        public decimal InsCoProfit { get; set; }
        public decimal OverHead { get; set; }
        public decimal FundOver { get; set; }
        public decimal HumanFund { get; set; }
        public decimal TotalNetPremuim { get; set; }
        public decimal BrokerCommission { get; set; }
        public decimal TotalPremuimPerson { get; set; }
        public decimal TotalPremuimGroup { get; set; }
        public string AgeGroupName { get; set; }
        public int AgeGroupID { get; set; }
        public int OfferTypeID { get; set; }
        public string OfferTypeName { get; set; }
    }
}
