//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryReportold
    {
        public string CustomerName { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime EndDate { get; set; }
        public string MemberName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<long> ClaimFormNum { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public string Expr1 { get; set; }
        public decimal NetPaymentAmt { get; set; }
        public string RejectNotes { get; set; }
        public int ProviderID { get; set; }
        public string ProviderName { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string BatchNumber { get; set; }
    }
}
