//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportData
    {
        public int ReportTypeID { get; set; }
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public string ReportNameAlt { get; set; }
        public string ReportUrl { get; set; }
        public string ReportUrlAlt { get; set; }
        public int ReportTransID { get; set; }
        public string ReportTableName { get; set; }
    }
}
