//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sa_CareItems
    {
        public int CI_Code { get; set; }
        public string CI_Namea { get; set; }
        public string CI_Namee { get; set; }
        public string Notes { get; set; }
        public string item_category { get; set; }
    }
}
