//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubBrokerData
    {
        public int SubBrokerID { get; set; }
        public string SubBrokerName { get; set; }
        public string Mobile { get; set; }
        public string EmailAdd { get; set; }
        public int BrokerID { get; set; }
    }
}
