//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianOnline.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellnessReport
    {
        public string CustomerName { get; set; }
        public int ApprovalID { get; set; }
        public Nullable<long> ApprovalCode { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ServiceName { get; set; }
        public decimal ServiceQnt { get; set; }
        public decimal ServiceUnitAmt { get; set; }
        public Nullable<decimal> ServiceAmt { get; set; }
        public string CardNumber { get; set; }
        public string MemberName { get; set; }
        public decimal DiscountPerc { get; set; }
        public Nullable<decimal> Service_Discount { get; set; }
        public Nullable<decimal> Service_Due { get; set; }
        public Nullable<decimal> Admin_Fees { get; set; }
        public Nullable<decimal> Invoice_DueAMT { get; set; }
    }
}
